Repository kubernetes/perf-tests, pull requests merged in 2018-04, with the labels that each got.

#95 fix misspelling of Kubernetes
  slo-monitor/src/main/slo-monitor.go
Labels: cncf-cla: yes, lgtm, size/XS

#109 Updating go version.
  .travis.yml
  verify/verify-gofmt.sh
Labels: cncf-cla: yes, lgtm, size/XS

#111 Fix wojtek-t`s login in OWNERS file
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#112 Keeping selected test name
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#113 Correcting perfdash image repo name
  perfdash/Makefile
  perfdash/README.md
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#101 Allowing ClusterLoader,Network and DNS Tests to run from kubetest
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#117 undefined values workaround
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#118 Typo fix: seperate->separate
  perfdash/www/Chart.js
Labels: approved, cncf-cla: yes, lgtm, size/XS
