Repository kubernetes/perf-tests, pull requests merged in 2018-09, with the labels that each got.

#214 ClusterLoader - Adding templating to test configs
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/codec.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#220 ClusterLoader - Rand template functions update
  clusterloader2/pkg/config/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#218 ClusterLoader - Adding parallelism
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#222 ClusterLoader - Fixing mapping creation
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#223 ClusterLoader - Changing to bundle ticker
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#224 Perfdash - etcd metrics fix
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#227 ClusterLoader - Adding test phase timer
  clusterloader2/pkg/measurement/common/test_phase_timer.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#230 ClusterLoader - Adding bool parsing from config
  clusterloader2/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#231 Update Alpine version for slo-monitor image
  slo-monitor/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#221 ClusterLoader - e2e measurements
  clusterloader2/pkg/measurement/common/metrics_for_e2e.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/BUILD
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/OWNERS
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/annotation_key_constants.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/doc.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/field_constants.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/json.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/objectreference.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/register.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/resource.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/taint.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/toleration.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/types.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/apis/core/zz_generated.deepcopy.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/BUILD
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/api_server_metrics.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/cluster_autoscaler_metrics.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/controller_manager_metrics.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/generic_metrics.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/kubelet_metrics.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/metrics_grabber.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/scheduler_metrics.go
  clusterloader2/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#219 ClusterLoader - Adding parallelism to wait_for_controlled_pods measurement
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/M
