Repository kubernetes/perf-tests, pull requests merged in 2018-11, with the labels that each got.

#242 ClusterLoader - density test update
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#277 ClusterLoader - Adding custom duration
  clusterloader2/api/extensions.go
  clusterloader2/api/types.go
  clusterloader2/pkg/tuningset/randomized_time_limited.go
  clusterloader2/pkg/tuningset/stepped_load.go
  clusterloader2/pkg/tuningset/time_limited.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#278 ClusterLoader - Adding measurement dispose
  clusterloader2/pkg/measurement/common/api_responsiveness.go
  clusterloader2/pkg/measurement/common/etcd_metrics.go
  clusterloader2/pkg/measurement/common/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/pod_startup_latency.go
  clusterloader2/pkg/measurement/common/profile.go
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/measurement/common/timer.go
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#280 ClusterLoader - Density test - PODS_PER_NODE
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#253 ClusterLoader - Updating load test
  clusterloader2/api/extensions.go
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#283 ClusterLoader - Removing stop action from load config
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#291 Fix some typos
  clusterloader/framework/util.go
  clusterloader2/pkg/measurement/util/perftype.go
  clusterloader2/pkg/state/namespaces_state.go
  slo-monitor/src/monitors/pod_monitor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#289 Doc & Script fixes
  clusterloader/README.md
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#285 ClusterLoader - Moving ClusterConfig global to MeasurementManager structure
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/api_responsiveness.go
  clusterloader2/pkg/measurement/common/etcd_metrics.go
  clusterloader2/pkg/measurement/common/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/profile.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/test/simple_context.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#284 ClusterLoader - Applying default params to test configs
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#294 ClusterLoader - Adding metric violation error
  clusterloader2/pkg/measurement/common/api_responsiveness.go
  clusterloader2/pkg/measurement/errors.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#286 ClusterLoader - Test metrics measurements bundle
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/timer.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/factory.go
  clusterloader2/pkg/util/error_list.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#297 ClusterLoader - Fixing test metrics bundle
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#298 ClusterLoader - Fixing pods status printing
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#299 ClusterLoader - Updating pod startup measurement logs
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/latency_metric.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#302 ClusterLoader - Updating pod startup measurement error text
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#305 Increment version number for slo-monitor.
  slo-monitor/Makefile
  slo-monitor/slo-monitor-deployment.yaml
  slo-monitor/slo-monitor-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#304 ClusterLoader - Moving errors to pkg/errors
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/errors/error_list.go
  clusterloader2/pkg/errors/metric_violation_error.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#306 ClusterLoader - Adding measurement String() method
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/timer.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#307 ClusterLoader - handling SLOs fails
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#308 ClusterLoader - Resource usage constrains
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/measurement/util/resource.go
  clusterloader2/pkg/test/simple_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#309 ClusterLoader - 5x100 density test update
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#313 ClusterLoader - Adding owner file to clusterloader2
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#311 Revert "ClusterLoader - 5x100 density test update"
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#314 ClusterLoader - Adding bundle restriction
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#315 ClusterLoader - Adding resource requests to latency pods
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#318 Cluster loader junit log
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/test/test.go
  clusterloader2/vendor/github.com/onsi/ginkgo/LICENSE
  clusterloader2/vendor/github.com/onsi/ginkgo/config/config.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/default_reporter.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/fake_reporter.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/junit_reporter.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/reporter.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/stenographer/console_logging.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/stenographer/fake_stenographer.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/stenographer/stenographer.go
  clusterloader2/vendor/github.com/onsi/ginkgo/reporters/teamcity_reporter.go
  clusterloader2/vendor/github.com/onsi/ginkgo/types/code_location.go
  clusterloader2/vendor/github.com/onsi/ginkgo/types/synchronization.go
  clusterloader2/vendor/github.com/onsi/ginkgo/types/types.go
  clusterloader2/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#290 Dns - Adding jsonify
  dns/jsonify/main.go
  dns/jsonify/vendor/github.com/golang/glog/LICENSE
  dns/jsonify/vendor/github.com/golang/glog/README
  dns/jsonify/vendor/github.com/golang/glog/glog.go
  dns/jsonify/vendor/github.com/golang/glog/glog_file.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/LICENSE
  dns/jsonify/vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  dns/jsonify/vendor/gopkg.in/yaml.v2/NOTICE
  dns/jsonify/vendor/gopkg.in/yaml.v2/README.md
  dns/jsonify/vendor/gopkg.in/yaml.v2/apic.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/decode.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/emitterc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/encode.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/go.mod
  dns/jsonify/vendor/gopkg.in/yaml.v2/parserc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/readerc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/resolve.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/scannerc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/sorter.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/writerc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/yaml.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/yamlh.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/yamlprivateh.go
  dns/jsonify/vendor/k8s.io/kubernetes/LICENSE
  dns/jsonify/vendor/k8s.io/kubernetes/test/e2e/perftype/BUILD
  dns/jsonify/vendor/k8s.io/kubernetes/test/e2e/perftype/perftype.go
  dns/jsonify/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#319 ClusterLoader - Adding scheduling throughput
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/util/pods.go
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#320 ClusterLoader - Correcting misspelled metric name
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#321 ClusterLoader - Minor measurement error fixes
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/S
