Repository kubernetes/perf-tests, pull requests merged in 2018-12, with the labels that each got.

#324 ClusterLoader: Pretty printing test summary
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#325 Allow to set masternode / masterip through CLI
  clusterloader2/README.md
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#322 ClusterLoader - Adding resource constraints to 100 nodes density test
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/util/util.go
  clusterloader2/testing/density/100_nodes/constraints.yaml
  clusterloader2/testing/density/100_nodes/override.yaml
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#328 ClusterLoader - Fixing test metrics bundle
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#323 Updating dns benchmark run script
  dns/README.md
  dns/run
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#329 Perfdash - Unknown job type fix
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#332 Perfdash - dns benchmark config
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#331 Dns benchmark - Fixing dns benchmark path
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#333 Dns benchmark - Adding numpy installation to run script
  dns/run
Labels: approved, cncf-cla: yes, lgtm, size/XS

#334 Perfdash - Removing empty labels
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#335 ClusterLoader - Minor logging fix
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#336 Dns benchmark - Fixing dns metrics units
  dns/jsonify/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#337 ClusterLoader - Overriding resource usage gathering for 2000 nodes test
  clusterloader2/testing/density/2000_nodes/override.yaml
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#338 ClusterLoader - Updating 100 nodes density constraints
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#339 Add not-ready/unreachable node tolerations ot density/load rcs.
  clusterloader2/testing/density/rc.yaml
  clusterloader2/testing/load/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#340 ClusterLoader- Fixing measurements for kubemark
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#342 Clusterloader - Measurement fixes
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/util/kubemark/kubemark.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#343 Add API to configure node killing in clusterloader2.
  clusterloader2/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#341 ClusterLoader - Fixing RC deletion handling
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#345 Migrate NodeKiller to clusterloader2.
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/util/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#346 Add a way to optionally enable chaos monkey in tests.
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/testing/chaosmonkey/override.yaml
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#347 Don't ignore error returned by ctx.GetChaosMonkey().Init.
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#348 Bug in chaos.Monkey: add missing go in m.nodeKiller.Run() call.
  clusterloader2/pkg/chaos/monkey.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#349 Reduce amount of unuseful logs
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#351 ClusterLoader - Adding 5k overrides
  clusterloader2/testing/density/5000_nodes/override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#352 ClusterLoader - Increasing lb-controller cpu constraint
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#354 Change perfdash to look for PodStartupLatency metrics in new place.
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#353 Change operationTimeout to 15m in scalability tests
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/measurement/util/latency_metric.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#356 Modify pod_startup_latency not to fail in case of missing schedule event.
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#358 Add Security contacts
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#360 ClusterLoader - Bumping up test resources
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#359 Dns benchmark files rename
  dns/run
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
