Repository kubernetes/perf-tests, pull requests merged in 2018-08, with the labels that each got.

#177 ClusterLoader - Updating measurement api
  clusterloader2/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#178 Improving clusterloader's Measurement API
  clusterloader/docs/design.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#179 Minor fixes in cluster-loader doc
  clusterloader/docs/design.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#176 ClusterLoader - Adding templating
  clusterloader2/api/types.go
  clusterloader2/pkg/config/codec.go
  clusterloader2/pkg/config/templateprovider.go
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#180 ClusterLoader - Adding measurement manager
  clusterloader2/pkg/measurement/factory.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#181 ClusterLoader - Adding json annotations to measurement api
  clusterloader2/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#182 ClusterLoader - Adding measurement manager to test context
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simplecontext.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#183 ClusterLoader - Adding measurement manger to test execution
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#184 ClusterLoader - Adding measurement util
  clusterloader2/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#185 ClusterLoader - Adding timer measurement
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/timer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#187 Adding Flags to run ClusterLoader, Netperf and DNS
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#175 ClusterLoader - Implementing different timers
  clusterloader2/pkg/ticker/simpletickerfactory.go
  clusterloader2/pkg/ticker/ticker.go
  clusterloader2/pkg/ticker/timer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#189 ClusterLoader - Renaming update to patch
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#190 ClusterLoader - API server latency
  clusterloader2/pkg/measurement/common/apicalllatency.go
  clusterloader2/pkg/measurement/util/latencymetric.go
  clusterloader2/pkg/measurement/util/perftype.go
  clusterloader2/pkg/measurement/util/prometheus.go
  clusterloader2/pkg/util/util.go
  clusterloader2/vendor/github.com/matttproud/golang_protobuf_extensions/LICENSE
  clusterloader2/vendor/github.com/matttproud/golang_protobuf_extensions/NOTICE
  clusterloader2/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/Makefile
  clusterloader2/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/decode.go
  clusterloader2/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/doc.go
  clusterloader2/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil/encode.go
  clusterloader2/vendor/github.com/prometheus/client_model/LICENSE
  clusterloader2/vendor/github.com/prometheus/client_model/NOTICE
  clusterloader2/vendor/github.com/prometheus/client_model/go/metrics.pb.go
  clusterloader2/vendor/github.com/prometheus/common/LICENSE
  clusterloader2/vendor/github.com/prometheus/common/NOTICE
  clusterloader2/vendor/github.com/prometheus/common/expfmt/decode.go
  clusterloader2/vendor/github.com/prometheus/common/expfmt/encode.go
  clusterloader2/vendor/github.com/prometheus/common/expfmt/expfmt.go
  clusterloader2/vendor/github.com/prometheus/common/expfmt/fuzz.go
  clusterloader2/vendor/github.com/prometheus/common/expfmt/text_create.go
  clusterloader2/vendor/github.com/prometheus/common/expfmt/text_parse.go
  clusterloader2/vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg/README.txt
  clusterloader2/vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg/autoneg.go
  clusterloader2/vendor/github.com/prometheus/common/model/alert.go
  clusterloader2/vendor/github.com/prometheus/common/model/fingerprinting.go
  clusterloader2/vendor/github.com/prometheus/common/model/fnv.go
  clusterloader2/vendor/github.com/prometheus/common/model/labels.go
  clusterloader2/vendor/github.com/prometheus/common/model/labelset.go
  clusterloader2/vendor/github.com/prometheus/common/model/metric.go
  clusterloader2/vendor/github.com/prometheus/common/model/model.go
  clusterloader2/vendor/github.com/prometheus/common/model/signature.go
  clusterloader2/vendor/github.com/prometheus/common/model/silence.go
  clusterloader2/vendor/github.com/prometheus/common/model/time.go
  clusterloader2/vendor/github.com/prometheus/common/model/value.go
  clusterloader2/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#195 Perfdash - config location
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#194 ClusterLoader - Adding basepath template provider
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/templateprovider.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/test/simplecontext.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#197 ClusterLoader - Int and float parsing fix
  clusterloader2/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#196 ClusterLoader - Density test
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#201 ClusterLoader- Adding summary logging
  clusterloader2/pkg/measurement/common/apicalllatency.go
  clusterloader2/pkg/measurement/common/timer.go
  clusterloader2/pkg/measurement/common/waitforpods.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#202 ClusterLoader - Adding clusterloader2 to run-e2e.sh
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#203 Adding echo to run-e2e script
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#204 ClusterLoader - Adding template functions
  clusterloader2/pkg/config/templatefunctions.go
  clusterloader2/pkg/config/templateprovider.go
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#206 ClusterLoader - Changing basename placeholder to name
  clusterloader2/pkg/test/simpletestexecutor.go
  clusterloader2/testing/density/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#207 ClusterLoader - Changing file naming convention
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/framework/config/client_config.go
  clusterloader2/pkg/measurement/common/api_call_latency.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
  clusterloader2/pkg/measurement/util/latency_metric.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/ticker/simple_ticker_factory.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#208 ClusterLoader - Adding test name to config
  clusterloader2/api/types.go
  clusterloader2/cmd/clusterloader.go
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#211 ClusterLoader - Api responsiveness fix
  clusterloader2/pkg/measurement/common/api_responsiveness.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#210 ClusterLoader - Allowing multiple tests
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/codec.go
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#212 ClusterLoader - Allowing multiple tests fix
  clusterloader2/pkg/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#216 Perfdash - updating config location
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
