Repository kubernetes/perf-tests, pull requests merged in 2018-07, with the labels that each got.

#146 Mention feedback loop as future enhancement of Cluster Loader
  clusterloader/docs/design.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#143 Perfdash: requesting builds data on demand
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/downloader.go
  perfdash/perfdash.go
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/L

#149 Perfdash - icon fix
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/index.html
  perfdash/www/k8s_logo.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#144 ClusterLoader - File unmarshaling
  clusterloader2/api/types.go
  clusterloader2/config/codec.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#150 ClusterLoader - removing ObjectType
  clusterloader2/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#152 Perfdash: adding x-axis label
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#148 ClusterLoader - Adding framework
  clusterloader2/framework/client/objects.go
  clusterloader2/framework/config/clientconfig.go
  clusterloader2/framework/framework.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#153 ClusterLoader - main
  clusterloader2/README.md
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/codec.go
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/framework/config/clientconfig.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#151 ClusterLoader - unmarshaling templates
  clusterloader2/pkg/config/codec.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#156 Perfdash: config for build ranges
  perfdash/Dockerfile
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/google-gcs-downloader.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#145 ClusterLoader - Adding test state
  clusterloader2/pkg/state/state.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#158 Perfdash: desabling animation
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#159 ClusterLoader - adding test executor interface
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#160 Perfdash: histogram
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#162 Update OWNERS for perf-dash
  perfdash/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#157 ClusterLoader - simple test implementation
  clusterloader2/pkg/test/simplecontext.go
  clusterloader2/pkg/test/simpletestexecutor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#161 Perfdash: category level
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/downloader.go
  perfdash/google-gcs-downloader.go
  perfdash/perfdash.go
  perfdash/www/index.html
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/L

#163 Change hit radius for perfdash click
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/Chart.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#165 Perfdash: changing le to <=
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#166 update the testgrid link for kubemark-100-benchmark perf-tests
  benchmark/docs/design.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#170 ClusterLoader - Adding execute object logic
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#155 ClusterLoader - Tuning ticker mock
  clusterloader2/pkg/ticker/ticker.go
  clusterloader2/pkg/ticker/timer.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#173 ClusterLoader - Vendor update
  clusterloader2/vendor/github.com/davecgh/go-spew/LICENSE
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/bypass.go
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/common.go
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/config.go
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/doc.go
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/dump.go
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/format.go
  clusterloader2/vendor/github.com/davecgh/go-spew/spew/spew.go
  clusterloader2/vendor/github.com/evanphx/json-patch/LICENSE
  clusterloader2/vendor/github.com/evanphx/json-patch/README.md
  clusterloader2/vendor/github.com/evanphx/json-patch/merge.go
  clusterloader2/vendor/github.com/evanphx/json-patch/patch.go
  clusterloader2/vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
  clusterloader2/vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  clusterloader2/vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  clusterloader2/vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  clusterloader2/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#167 ClusterLoader - Adding read template with cache
  clusterloader2/pkg/config/templateprovider.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simplecontext.go
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#172 ClusterLoader - Object update
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/test/simpletestexecutor.go
Labels: approved, cncf-cla: yes, lgtm, size/M
