Repository kubernetes/perf-tests, pull requests merged in 2018-06, with the labels that each got.

#133 Adding scheduler throughput and scheduling latency to perfdash
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#134 Update Cluster Loader design
  clusterloader/docs/design.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#136 Scheduler latency update
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#140 Updating boilerplate script
  verify/boilerplate/boilerplate.py
Labels: approved, cncf-cla: yes, lgtm, size/XS

#138 Perfdash: splitting test name selector
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/downloader.go
  perfdash/google-gcs-downloader.go
  perfdash/perfdash.go
  perfdash/www/index.html
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#141 Perfdash units fix
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#135 Cluster loader - API structures
  clusterloader2/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#131 Create output report per iteration
  network/benchmarks/netperf/launch.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#147 Fixing verify_golint.sh for go1.10+ versions
  verify/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#128 Add reporting of CPU usage for iperf to orchestrator
  network/benchmarks/netperf/nptest/nptest.go
Labels: approved, cncf-cla: yes, lgtm, size/S
