Repository kubernetes/perf-tests, pull requests merged in 2019-06, with the labels that each got.

#549 Update travis go version to 1.12.
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#550 Add mm4tt to k/perf-tests approvers.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#551 Add proto support to logviewer/
  _logviewer/.gitignore
  _logviewer/BUILD.bazel
  _logviewer/OWNERS
  _logviewer/README.md
  _logviewer/WORKSPACE
  _logviewer/example/BUILD.bazel
  _logviewer/example/README.md
  _logviewer/example/bin/BUILD.bazel
  _logviewer/example/bin/test.go
  _logviewer/example/protos/BUILD.bazel
  _logviewer/example/protos/test.proto
  _logviewer/example/protos2/BUILD.bazel
  _logviewer/example/protos2/test2.proto
Labels: approved, cncf-cla: yes, lgtm, size/L

#555 Use strings.Replace instead strings.ReplaceAll to keep compatibility with go1.11.5
  .travis.yml
  clusterloader2/pkg/config/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#548 Perfdash - Extracting config paths to flags
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/google-gcs-downloader.go
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#556 Master dashboard: set min value on Y axis to 0.
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#562 ClusterLoader - Adding kubemark load test override
  clusterloader2/testing/load/kubemark/throughput_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#560 Perfdash - Reading config from file system
  perfdash/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#558 Use jq to format Grafana dashboards in json files
  .travis.yml
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/network-programming-latency.json
  verify/verify-dashboard-format.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XXL

#565 API responsiveness SLO: move filtering to Prometheus
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#564 Perfdash - Making gcs configurable
  perfdash/google-gcs-downloader.go
  perfdash/perfdash.go
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/L

#568 Extract common code for Prometheus-based measurements.
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#566 Perdash - version 2.0
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#570 Add support for StringSliceEnvVar flag.
  clusterloader2/pkg/flags/flags.go
  clusterloader2/pkg/flags/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#571 Exclude _logviewer from tests
  verify/test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#557 Recording rule for Network Programming Latency
  clusterloader2/pkg/config/codec.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/manifests/dashboards/network-programming-latency.json
  clusterloader2/pkg/prometheus/manifests/default/kube-proxy-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeProxy.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
  clusterloader2/testing/prometheus/scrape-kube-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#574 Create an interface for querying Prometheus from measurements.
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
  clusterloader2/pkg/measurement/util/prometheus.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#577 Perfdash - Merging component versions
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/parser.go
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#580 Add a measurement for network programming latency
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/network_programming_test.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
  clusterloader2/pkg/measurement/util/prometheus.go
  clusterloader2/testing/load/config.yaml
  clusterloader2/vendor/github.com/pmezard/go-difflib/LICENSE
  clusterloader2/vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  clusterloader2/vendor/github.com/stretchr/objx/LICENSE
  clusterloader2/vendor/github.com/stretchr/objx/README.md
  clusterloader2/vendor/github.com/stretchr/objx/Taskfile.yml
  clusterloader2/vendor/github.com/stretchr/objx/accessors.go
  clusterloader2/vendor/github.com/stretchr/objx/conversions.go
  clusterloader2/vendor/github.com/stretchr/objx/doc.go
  clusterloader2/vendor/github.com/stretchr/objx/go.mod
  clusterloader2/vendor/github.com/stretchr/objx/go.sum
  clusterloader2/vendor/github.com/stretchr/objx/map.go
  clusterloader2/vendor/github.com/stretchr/objx/mutations.go
  clusterloader2/vendor/github.com/stretchr/objx/security.go
  clusterloader2/vendor/github.com/stretchr/objx/tests.go
  clusterloader2/vendor/github.com/stretchr/objx/type_specific.go
  clusterloader2/vendor/github.com/stretchr/objx/type_specific_codegen.go
  clusterloader2/vendor/github.com/stretchr/objx/value.go
  clusterloader2/vendor/github.com/stretchr/testify/Gopkg.lock
  clusterloader2/vendor/github.com/stretchr/testify/Gopkg.toml
  clusterloader2/vendor/github.com/stretchr/testify/LICENSE
  clusterloader2/vendor/github.com/stretchr/testify/README.md
  clusterloader2/vendor/github.com/stretchr/testify/assert/assertion_format.go
  clusterloader2/vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  clusterloader2/vendor/github.com/stretchr/testify/assert/assertion_forward.go
  clusterloader2/vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  clusterloader2/vendor/github.com/stretchr/testify/assert/assertion_order.go
  clusterloader2/vendor/github.com/stretchr/testify/assert/assertions.go
  clusterloader2/vendor/github.com/stretchr/testify/assert/doc.go
  clusterloader2/vendor/github.com/stretchr/testify/assert/errors.go
  clusterloader2/vendor/github.com/stretchr/testify/assert/forward_assertions.go
  clusterloader2/vendor/github.com/stretchr/testify/assert/http_assertions.go
  clusterloader2/vendor/github.com/stretchr/testify/doc.go
  clusterloader2/vendor/github.com/stretchr/testify/go.mod
  clusterloader2/vendor/github.com/stretchr/testify/go.sum
  clusterloader2/vendor/github.com/stretchr/testify/http/doc.go
  clusterloader2/vendor/github.com/stretchr/testify/http/test_response_writer.go
  clusterloader2/vendor/github.com/stretchr/testify/http/test_round_tripper.go
  clusterloader2/vendor/github.com/stretchr/testify/mock/doc.go
  clusterloader2/vendor/github.com/stretchr/testify/mock/mock.go
  clusterloader2/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#582 Add apiserver_init_events_total metric to e2e metrics
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#583 Fix unchecked errors in clusterloader2 code.
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/simple/timer.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#586 Fix typo in measurement name.
  clusterloader2/pkg/measurement/common/slos/network_programming.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#587 Fix scalability tests
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
