Repository kubernetes/perf-tests, pull requests merged in 2019-09, with the labels that each got.

#764 Fix: simple_graph cannot use Targets, use plain Graph instead.
  clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#766 Fix container_* metrics
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#768 Fix memory leaks in probes.
  probes/Makefile
  probes/cmd/main.go
  probes/pkg/ping/client/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#770 Make deployment.yaml ignore .ENABLE_CONFIGMAPS|SECRETS vars
  clusterloader2/testing/load/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#769 Bump probes to v0.0.4.
  clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#765 Optionally scrape kubelets in tests. Skip test pods.
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubelet.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#772 Implement IfThenElse template func
  clusterloader2/pkg/config/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#767 Enable secrets and configmaps in load test
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/configmap.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/experimental/deployment.yaml
  clusterloader2/testing/load/experimental/extended_config.yaml
  clusterloader2/testing/load/experimental/service.yaml
  clusterloader2/testing/load/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#774 Grafana: create DNS-specific dashboard
  clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py
  clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/dns.json
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py
  clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#775 Add override files for enabling statefulsets and PVs
  clusterloader2/testing/load/experimental/overrides/enable_pvs.yaml
  clusterloader2/testing/load/experimental/overrides/enable_statefulsets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#773 Grafana: plot ping rate, ping error rate and probes memory usage
  clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/network.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#776 Create StatefulSets in load test
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/statefulset.yaml
  clusterloader2/testing/load/statefulset_service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#771 Cache Prometheus persistent disk name before running tests
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#778 Do not automount default serviceAccount in node tests
  clusterloader2/testing/node-throughput/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#780 Add override for enabling DaemonSets
  clusterloader2/testing/load/experimental/overrides/enable_daemonsets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#781 Fix group label in statefulset.yaml
  clusterloader2/testing/load/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#785 Grafana: improve dashboard for network-latency probes.
  clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/network.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#784 Increase number of probes running in tests
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#789 Add an experiment for simply latency query.
  clusterloader2/testing/experiments/use_simple_latency_query.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#788 Fix logic for checking if at least one etcd target is available
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#800 ClusterLoader: Log step's errors
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#801 Extend load test to cover Jobs
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#795 Add option to use simple latency query for API latency.
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/network_programming_test.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
  clusterloader2/pkg/measurement/util/prometheus.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#802 Extend load test to cover PersistentVolumes
  clusterloader2/api/types.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/pvc.yaml
  clusterloader2/testing/load/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#805 Set priorityClassName for DaemonSet pods
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/daemonset-priorityclass.yaml
  clusterloader2/testing/load/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#806 Restore PROMETHEUS_SCRAPE_KUBE_PROXY guarding
  clusterloader2/pkg/prometheus/manifests/default/kube-proxy-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeProxy.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/prometheus/not-scrape-kube-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#808 Prometheus: log example not ready target
  clusterloader2/pkg/prometheus/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#809 Grafana: add etcd wal fsync duration panel
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#810 Grafana: collapse panels on master dashboard
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#813 ClusterLoader - Using unschedulable spec
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#815 Bump daemonset parallelism in load test
  clusterloader2/testing/load/daemonset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#817 Add local dev instructions to perfdash readme
  perfdash/README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#818 Add storage experimental test suite
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/empty_test_name/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/suite.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M
