Repository kubernetes/perf-tests, pull requests merged in 2019-08, with the labels that each got.

#725 ClusterLoader - Disk snapshot name verify
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/util.go
  clusterloader2/pkg/prometheus/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#639 Old style exceptions -> new style for Python 3
  dns/py/data.py
  dns/py/runner.py
  verify/verify-flags-underscore.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#687 Use deployment instead of raw pod for storage perf tests
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/configmap/deployment_with_configmap.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/configmap/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/configmap/pod_with_configmap.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/downwardapi/deployment_with_downwardapi.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/downwardapi/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/downwardapi/pod_with_downwardapi.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/emptydir/deployment_with_emptydir.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/emptydir/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/emptydir/pod_with_emptydir.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/deployment_with_pvc.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/pod_with_pvc.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/secret/deployment_with_secret.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/secret/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/secret/pod_with_secret.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/storage, size/L

#728 ClusterLoader - Service creation latency logs fix
  clusterloader2/pkg/measurement/common/service_creation_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#729 Bump pod churn in node-throughput test
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#733 Improve logging around Prometheus snapshoting
  clusterloader2/pkg/prometheus/experimental.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#721 ClusterLoader - Adding TestSuite api
  clusterloader2/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#723 add function to wait for available PVs
  clusterloader2/pkg/measurement/common/wait_for_pvs.go
  clusterloader2/pkg/measurement/util/object_store.go
  clusterloader2/pkg/measurement/util/pvs.go
  clusterloader2/pkg/measurement/util/wait_for_pvs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#724 wait for PV to be deleted in storage tests
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/override.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#705 add functionality to deploy cloud-sa secret and driver
  clusterloader2/drivers/gcp-csi-driver-stable.yaml
  clusterloader2/run-e2e.sh
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/pvc.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/usecsi.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#731 ClusterLoader - Test suite
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/template_provider.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#727 Remove ENABLE_PROBES experiment.
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml
  clusterloader2/testing/load/experimental/extended_config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#736 Disable "NetworkProgrammingLatency" measurement in kubemark
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#726 Remove PROMETHEUS_SCRAPE_KUBE_PROXY experiment.
  clusterloader2/pkg/prometheus/manifests/default/kube-proxy-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeProxy.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml
  clusterloader2/testing/load/experimental/extended_config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#738 Reduce node test throughput
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#741 ClusterLoader - Adding prometheus flags
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/prometheus.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#686 Storage perf tests decrease volumes and pod number
  clusterloader2/testing/experimental/storage/pod-startup/max_volumes_per_node/25_pods_per_node/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/test-result/volume_podstartup_time_results.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/storage, size/L

#569 Add code for logviewer
  _logviewer/WORKSPACE
  _logviewer/go.mod
  _logviewer/go.sum
  _logviewer/mixer-client/BUILD.bazel
  _logviewer/mixer-client/main.go
  _logviewer/mixer/BUILD.bazel
  _logviewer/mixer/main.go
  _logviewer/mixer/mixer_test.go
  _logviewer/mixer/request/BUILD.bazel
  _logviewer/mixer/request/request.proto
  _logviewer/worker/BUILD.bazel
  _logviewer/worker/gcsreader.go
  _logviewer/worker/main.go
  _logviewer/worker/parsing.go
  _logviewer/worker/parsing_test.go
  _logviewer/worker/work/BUILD.bazel
  _logviewer/worker/work/work.proto
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XXL

#739 Refactor probes.go so that there is a single prober enabled per instance
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/latency_metric.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml
  clusterloader2/testing/load/experimental/extended_config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#743 Perfdash - old metrics cleanup
  perfdash/config.go
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#732 Grafana: use concise legends
  *.json
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/regenerate.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#747 Fix buckets in ping-client probe.
  probes/pkg/ping/client/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#746 Bump version of probes in ping-{client,server} to 0.0.3
  clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#744 Refactoring of Granafa dashboard setup.
  clusterloader2/pkg/prometheus/manifests/dashboards/Makefile
  clusterloader2/pkg/prometheus/manifests/dashboards/README.md
  clusterloader2/pkg/prometheus/manifests/dashboards/__init__.py
  clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/requirements.txt
  verify/boilerplate/boilerplate.py.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#749 Perfdash - Adding load etcd metrics
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#709 Run DNS probes in tests
  clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-service.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-serviceMonitor.yaml
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml
  clusterloader2/testing/load/experimental/extended_config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#748 Grafana: create SLO dashboard with experimental panels
  clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/slo.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
  clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#750 Grafana: extend network-related dashboard
  clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/network-programming-latency.json
  clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/network.json
  clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#745 Show DNS lookup latency in PerfDash.
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#752 Do not run probes if Prometheus is disabled.
  clusterloader2/pkg/measurement/common/probes/probes.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#751 Cleanup old experiments: network latency probes and kube-proxy scraping
  clusterloader2/testing/experiments/probes.yaml
  clusterloader2/testing/prometheus/scrape-kube-proxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#754 ClusterLoader - Supporting multiple service creation latencies
  clusterloader2/pkg/measurement/common/service_creation_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#737 ClusterLoader - Adding test scenario to config
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#753 Create a separate OWNERS file for Grafana dashboards.
  clusterloader2/pkg/prometheus/manifests/dashboards/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#756 Allow for configuring SLO-monitor with kubeconfig file
  slo-monitor/go.mod
  slo-monitor/go.sum
  slo-monitor/src/main/slo-monitor.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#757 Update slo-monitor to 0.12 version
  slo-monitor/Makefile
  slo-monitor/slo-monitor-deployment.yaml
  slo-monitor/slo-monitor-pod.yaml
  slo-monitor/vendor/k8s.io/autoscaler/LICENSE
  slo-monitor/vendor/k8s.io/autoscaler/cluster-autoscaler/config/autoscaling_options.go
  slo-monitor/vendor/k8s.io/autoscaler/cluster-autoscaler/config/const.go
  slo-monitor/vendor/k8s.io/autoscaler/cluster-autoscaler/config/kubernetes.go
  slo-monitor/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, size/XL

#740 Added a simple scale test for L4ILB.
  clusterloader2/testing/l4ilb/config.yaml
  clusterloader2/testing/l4ilb/dep.yaml
  clusterloader2/testing/l4ilb/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#759 Decrease pod throughput in node throughput tests
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
