Repository kubernetes/perf-tests, pull requests merged in 2019-02, with the labels that each got.

#395 ClusterLoader - Updating README
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#399 ClusterLoader- Allowing inactive pods
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#405 Add more descriptive error messages.
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#403 ClusterLoader - Replacing glog with klog
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/flags/flags.go
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/simple/timer.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go
  clusterloader2/pkg/measurement/util/kubemark/kubemark.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/util/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#407 Add basic test for node throughput
  clusterloader2/testing/node-throughput/config.yaml
  clusterloader2/testing/node-throughput/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#408 Don't kill the same node twice in NodeKiller.
  clusterloader2/pkg/chaos/nodes.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#410 add kubemark ssh key env variable
  clusterloader2/pkg/measurement/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#412 Handle tombstones in clusterloader2
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#416 Benchmark - Vendor update
  benchmark/Godeps/Godeps.json
  benchmark/vendor/k8s.io/contrib/test-utils/utils/utils.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#418 Bump up kube-proxy cpu constraint
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#417 ClusterLoader - Pod startup log
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/selector.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#421 Customize pod throughput in node-throughput test
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#409 ClusterLoader- Adding node killer log prefix
  clusterloader2/pkg/chaos/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#426 ClusterLoader - Add dynamic clients for measurement manager
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/test/simple_context.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#427 Increase saturationRCHardTimeout to 20min
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#429 Tune prometheus stack to make it work for 5k node clusters
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-clusterRole.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-clusterRoleBinding.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-role.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-roleBinding.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-service.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-serviceAccount.yaml
  clusterloader2/pkg/prometheus/manifests/kube-state-metrics-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/manifests/node-exporter-clusterRole.yaml
  clusterloader2/pkg/prometheus/manifests/node-exporter-clusterRoleBinding.yaml
  clusterloader2/pkg/prometheus/manifests/node-exporter-daemonset.yaml
  clusterloader2/pkg/prometheus/manifests/node-exporter-service.yaml
  clusterloader2/pkg/prometheus/manifests/node-exporter-serviceAccount.yaml
  clusterloader2/pkg/prometheus/manifests/node-exporter-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-apiService.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-clusterRole.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-clusterRoleBinding.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-clusterRoleBindingDelegator.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-clusterRoleServerResources.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-configMap.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-roleBindingAuthReader.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-service.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-adapter-serviceAccount.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-serviceMonitorKubeProxy.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-serviceMonitorKubelet.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#428 ClusterLoader - refine wait_for_controlled_pods.go clients data structure
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#431 Disable login in Grafana.
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#432 Add ability to tear down prometheus stack.
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/prometheus.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#433 Change prometheus flags to be env flags.
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/flags/flags.go
  clusterloader2/pkg/flags/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#425 ClusterLoader - Add unstructured support for runtimeobjects.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#424 ClusterLoader - Limiting pod startup logs to worst 100 pods
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#435 Tear down prometheus stack also on failed tests.
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#436 Clusterloader - update vendor client-go dynamic package
  clusterloader2/vendor/k8s.io/client-go/dynamic/dynamicinformer/informer.go
  clusterloader2/vendor/k8s.io/client-go/dynamic/dynamicinformer/interface.go
  clusterloader2/vendor/k8s.io/client-go/dynamic/dynamiclister/interface.go
  clusterloader2/vendor/k8s.io/client-go/dynamic/dynamiclister/lister.go
  clusterloader2/vendor/k8s.io/client-go/dynamic/dynamiclister/shim.go
  clusterloader2/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#438 ClusterLoader - Replace clientset by dynamic client
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
