Repository kubernetes/perf-tests, pull requests merged in 2019-04, with the labels that each got.

#434 ClusterLoader - ApiResponsiveness measurement
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/measurement/util/prometheus.go
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#471 Extract CheckTargetsReady method.
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/prometheus/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#472 Fix newly added CheckTargetsReady method :)
  clusterloader2/pkg/prometheus/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#473 Fix typo in density config.
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#476 Pull prometheus images from gcr.io.
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#477 Start gathering controller-manager profiles
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#478 Gather cpu and memory profiles periodically
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#480 Log prometheus-k8s events on stack set up failures
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#482 Extract ApplyTemplatedManifests method.
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#483 Make ApplyTemplatedManifests accept ApiCallOptions.
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#484 ClusterLoader - Adding profile name
  clusterloader2/pkg/measurement/common/simple/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#486 Revert "ClusterLoader - Copying tests to head/ and legacy/"
  clusterloader2/testing/head/chaosmonkey/override.yaml
  clusterloader2/testing/head/density/100_nodes/constraints.yaml
  clusterloader2/testing/head/density/100_nodes/override.yaml
  clusterloader2/testing/head/density/2000_nodes/override.yaml
  clusterloader2/testing/head/density/5000_nodes/override.yaml
  clusterloader2/testing/head/density/600_nodes/high_density_override.yaml
  clusterloader2/testing/head/density/config.yaml
  clusterloader2/testing/head/density/rc.yaml
  clusterloader2/testing/head/load/config.yaml
  clusterloader2/testing/head/load/kubemark/500_nodes/override.yaml
  clusterloader2/testing/head/load/rc.yaml
  clusterloader2/testing/head/load/service.yaml
  clusterloader2/testing/head/node-throughput/config.yaml
  clusterloader2/testing/head/node-throughput/rc.yaml
  clusterloader2/testing/legacy/chaosmonkey/override.yaml
  clusterloader2/testing/legacy/density/100_nodes/constraints.yaml
  clusterloader2/testing/legacy/density/100_nodes/override.yaml
  clusterloader2/testing/legacy/density/2000_nodes/override.yaml
  clusterloader2/testing/legacy/density/5000_nodes/override.yaml
  clusterloader2/testing/legacy/density/600_nodes/high_density_override.yaml
  clusterloader2/testing/legacy/density/config.yaml
  clusterloader2/testing/legacy/density/rc.yaml
  clusterloader2/testing/legacy/load/config.yaml
  clusterloader2/testing/legacy/load/kubemark/500_nodes/override.yaml
  clusterloader2/testing/legacy/load/rc.yaml
  clusterloader2/testing/legacy/load/service.yaml
  clusterloader2/testing/legacy/node-throughput/config.yaml
  clusterloader2/testing/legacy/node-throughput/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#487 Add legacy/ directories to tests
  clusterloader2/testing/density/legacy/100_nodes/constraints.yaml
  clusterloader2/testing/density/legacy/100_nodes/override.yaml
  clusterloader2/testing/density/legacy/2000_nodes/override.yaml
  clusterloader2/testing/density/legacy/5000_nodes/override.yaml
  clusterloader2/testing/density/legacy/600_nodes/high_density_override.yaml
  clusterloader2/testing/density/legacy/config.yaml
  clusterloader2/testing/density/legacy/rc.yaml
  clusterloader2/testing/load/legacy/config.yaml
  clusterloader2/testing/load/legacy/kubemark/500_nodes/override.yaml
  clusterloader2/testing/load/legacy/rc.yaml
  clusterloader2/testing/load/legacy/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#474 Probes - boilerplate and first probe
  probes/Dockerfile
  probes/Makefile
  probes/OWNERS
  probes/README.md
  probes/cmd/main.go
  probes/go.mod
  probes/go.sum
  probes/pkg/metrics/metrics.go
  probes/pkg/ping/client/client.go
  probes/pkg/ping/server/server.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#488 Prepare for adding service-proxy-name label for half of the services
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/testing/load/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#491 ClusterLoader - Fixing api calls metric name
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#492 Increment version number for slo-monitor to 0.11.1
  slo-monitor/slo-monitor-deployment.yaml
  slo-monitor/slo-monitor-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#495 Fail ClusterLoader2 if there are no schedulable nodes.
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#496 Perfdash - Run id fix
  perfdash/Godeps/Godeps.json
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/google-gcs-downloader.go
  perfdash/vendor/github.com/ghodss/yaml/.gitignore
  perfdash/vendor/github.com/ghodss/yaml/.travis.yml
  perfdash/vendor/github.com/ghodss/yaml/yaml_test.go
  perfdash/vendor/github.com/golang/glog/glog_test.go
  perfdash/vendor/golang.org/x/net/context/context.go
  perfdash/vendor/golang.org/x/net/context/go17.go
  perfdash/vendor/golang.org/x/net/context/go19.go
  perfdash/vendor/golang.org/x/net/context/pre_go17.go
  perfdash/vendor/golang.org/x/net/context/pre_go19.go
  perfdash/vendor/gopkg.in/check.v1/.gitignore
  perfdash/vendor/gopkg.in/check.v1/.travis.yml
  perfdash/vendor/gopkg.in/check.v1/LICENSE
  perfdash/vendor/gopkg.in/check.v1/README.md
  perfdash/vendor/gopkg.in/check.v1/TODO
  perfdash/vendor/gopkg.in/check.v1/benchmark.go
  perfdash/vendor/gopkg.in/check.v1/check.go
  perfdash/vendor/gopkg.in/check.v1/checkers.go
  perfdash/vendor/gopkg.in/check.v1/helpers.go
  perfdash/vendor/gopkg.in/check.v1/printer.go
  perfdash/vendor/gopkg.in/check.v1/reporter.go
  perfdash/vendor/gopkg.in/check.v1/run.go
  perfdash/vendor/gopkg.in/yaml.v2/.travis.yml
  perfdash/vendor/gopkg.in/yaml.v2/decode_test.go
  perfdash/vendor/gopkg.in/yaml.v2/encode_test.go
  perfdash/vendor/gopkg.in/yaml.v2/example_embedded_test.go
  perfdash/vendor/gopkg.in/yaml.v2/suite_test.go
  perfdash/vendor/k8s.io/contrib/test-utils/utils/bucket.go
  perfdash/vendor/k8s.io/contrib/test-utils/utils/utils.go
  perfdash/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#490 Allow for differentiating different summaries from the same measurement
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/simple/timer.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#497 Benchmark - Run id fix
  benchmark/Godeps/Godeps.json
  benchmark/pkg/metricsfetcher/runselector/schemes/last_n_hours.go
  benchmark/pkg/metricsfetcher/runselector/schemes/last_n_runs.go
  benchmark/pkg/metricsfetcher/util/mock_util.go
  benchmark/pkg/metricsfetcher/util/util.go
  benchmark/vendor/k8s.io/contrib/test-utils/utils/bucket.go
  benchmark/vendor/k8s.io/contrib/test-utils/utils/utils.go
  benchmark/vendor/k8s.io/kubernetes/test/e2e/perftype/perftype.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#493 ClusterLoader - Adding api reposiveness prometheus to tests
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#500 Add CloudProvider to the MeasurementConfig.
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/test/simple_context.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#502 ClusterLoader - extracting prometheus query execution to util
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/util/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#504 Set the prometheus data retention to 7d
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#505 Pre-work to monitoring kubemark via internal IP.
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/prometheus.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#475 Framework for running Probes in ClusterLoader2
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-client-service.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-client-serviceMonitor.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-server-service.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-server-serviceMonitor.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/prometheus-role.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/prometheus-roleBinding.yaml
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#494 Rebase slo-monitor to distroless
  slo-monitor/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#508 Add missing prometheus services.
  clusterloader2/pkg/prometheus/manifests/default/kube-controller-manager-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/kube-scheduler-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#513 Don't drop any kube-apiserver metrics.
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorApiserver.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/prometheus-serviceMonitorApiserver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#510 Set MasterInternalIp in completeConfig if not set.
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/util/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#509 Do not use klog.Fatalf as it prints stacktrace. Use os.Exit(1) instead.
  .gitignore
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#511 Unify MasterIp variable used in prometheus templates.
  clusterloader2/pkg/prometheus/manifests/kubemark/kube-apiserver-endpoints.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#516 Store provider instead of isKubemark in PrometheusController
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#512 Scrape master's components every 5s.
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorApiserver.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeControllerManager.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeScheduler.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#515 Monitor kubemark master's components via Prometheus.
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/prometheus-serviceMonitorApiserver.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#514 Start monitoring master's kubelet (non-kubemark)
  clusterloader2/pkg/prometheus/manifests/default/master-kubelet-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/default/master-kubelet-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorMasterKubelet.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#499 ClusterLoader - Adding generic summary
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/measurement/common/simple/etcd_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/simple/timer.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/summary.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#521 ClusterLoader - Fixing measurements
  clusterloader2/pkg/measurement/common/simple/profile.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
