Repository kubernetes/perf-tests, pull requests merged in 2019-12, with the labels that each got.

#917 Update a Website link
  benchmark/docs/design.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#914 Use APIResponsivenessPrometheusSimple instead of APIResponsiveness.
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#901 [issuefix]:clusterloader2 testing result missing ControllerManagerMet…
  clusterloader2/pkg/measurement/common/metrics_for_e2e.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#920 Add github.com/go-errors/errors to CL2 vendor
  clusterloader2/vendor/github.com/go-errors/errors/LICENSE.MIT
  clusterloader2/vendor/github.com/go-errors/errors/README.md
  clusterloader2/vendor/github.com/go-errors/errors/cover.out
  clusterloader2/vendor/github.com/go-errors/errors/error.go
  clusterloader2/vendor/github.com/go-errors/errors/parse_panic.go
  clusterloader2/vendor/github.com/go-errors/errors/stackframe.go
  clusterloader2/vendor/vendor.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#906 Start enforcing scheduler throughput in density test
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#921 Cl2: Make CL2_* envs available in templates
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/config/template_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#913 Allow Prometheus to run on a tainted heapster node.
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#923 Use Measurement's indentifier in logging.
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#924 Log response body when there is an error from Prometheus
  clusterloader2/pkg/measurement/util/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#928 Increase maxSamples to 100000000 (from default 50000000).
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#927 Implement fetching prow config from directories
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/github-configs-fetcher.go
  perfdash/google-gcs-downloader.go
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#931 Add sig-release GCE-100 jobs to perfdash
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#915 Remove APIResponsiveness
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#930 Support for windows nodes
  clusterloader2/testing/node-throughput/config.yaml
  clusterloader2/testing/node-throughput/rc.yaml
  clusterloader2/testing/node-throughput/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#933 add scheduling cycle e2e latency
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#937 Ability to add Prometheus port firewall rule
  run-e2e-with-prometheus-fw-rule.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#935 Use APIResponsivenessPrometheusSimple in legacy test configs.
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#934 Perfdash: Improve perfdash logging
  perfdash/config.go
  perfdash/downloader.go
  perfdash/github-configs-fetcher.go
  perfdash/google-gcs-downloader.go
  perfdash/parser.go
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#939 Implement GlobalQPSLoad tuning set.
  clusterloader2/api/types.go
  clusterloader2/pkg/tuningset/global_qps_load.go
  clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#938 Update perfdash README with deployment instructions
  perfdash/README.md
  perfdash/deploy.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#941 Make mborsz approver in CL2
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#942 Make mborsz approver in CL2 (1.17)
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#943 Make oxddr and mborsz approvers in CL2 (1.16)
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#946 Make oxddr and mborsz approvers in CL2 (1.13)
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#947 Make oxddr and mborsz approvers in CL2 (1.12)
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#945 Make oxddr and mborsz approvers in CL2 (1.14)
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#944 Make oxddr and mborsz approvers in CL2 (1.15)
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#891 Enabled HA support for profile measurements
  clusterloader2/pkg/measurement/common/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#950 Fix GlobalQPSLoad to really share rate.Limiter
  clusterloader2/pkg/tuningset/global_qps_load.go
  clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#918 Improve Grafana dashboards
  clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/slo.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#951 Profile measurements should warn instead of fail on lack of master IPs
  clusterloader2/pkg/measurement/common/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#952 ClusterLoader - Legacy latency pod memory update (1.13)
  clusterloader2/testing/density/legacy/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#953 ClusterLoader - latency pod memory update (1.14)
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/legacy/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#954 ClusterLoader - Legacy latency pod memory update (1.15)
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/legacy/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#955 ClusterLoader - Legacy latency pod memory update (1.12)
  clusterloader2/testing/density/legacy/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#960 Add flag to override the prometheus snapshot name (1.15)
  clusterloader2/pkg/prometheus/experimental.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#958 Add flag to override the prometheus snapshot name (1.13)
  clusterloader2/pkg/prometheus/experimental.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#959 Add flag to override the prometheus snapshot name (1.14)
  clusterloader2/pkg/prometheus/experimental.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS
