Repository kubernetes/perf-tests, pull requests merged in 2019-11, with the labels that each got.

#845 Refactor master-ip manifests
  clusterloader2/pkg/prometheus/manifests/default/kube-controller-manager-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/kube-scheduler-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/master-ip/master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/default/master-ip/master-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorApiserver.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeControllerManager.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeScheduler.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/prometheus-role.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/prometheus-roleBinding.yaml
  clusterloader2/pkg/prometheus/manifests/master-ip/README.md
  clusterloader2/pkg/prometheus/manifests/master-ip/master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/master-ip/master-service.yaml
  clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#885 Format errors from APIResponsiveness* measurements uniformly
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#886 Perfdash - Updating default storage url
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#888 Check division by zero in template func
  clusterloader2/pkg/config/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#884 Allow for 2 restarts of CoreDNS in tests.
  clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#890 ServiceCreationLatency handle ClusterIP and NodePort type of service
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/measurement/common/service_creation_latency.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#892 Fix some err check and remove some unused values
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/pkg/measurement/common/service_creation_latency.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/kubelet/kubelet.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#896 Add missing start for APIResponsivenessPrometheusSimple
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#899 Minor change: add some debug log and fix a typo
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#898 Fix a few spelling mistakes.
  clusterloader2/pkg/measurement/util/wait_for_pods.go
  clusterloader2/pkg/measurement/util/wait_for_pvcs.go
  clusterloader2/pkg/measurement/util/wait_for_pvs.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#900 Add Sleep measurement
  clusterloader2/README.md
  clusterloader2/pkg/measurement/common/sleep.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#894 Make .Namespace variable to be available in test specs
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#903 Add last restart reason to system pod metrics
  clusterloader2/pkg/measurement/common/system_pod_metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#904 Start validating the scheduler throughput in density test
  clusterloader2/pkg/measurement/common/scheduling_throughput.go
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#905 Revert "Start enforcing scheduler throughput to be 90+ in density test"
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#883 Use sum-rate instead of rate for probes lookup rate.
  clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/dns.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#907 Ability to add Prometheus port firewall rule
  run-e2e-with-prometheus-fw-rule.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#908 Allow a single restart of master components
  clusterloader2/testing/experiments/ignore_known_gce_container_restarts.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#909 Clean up Prometheus firewall rule after test
  run-e2e-with-prometheus-fw-rule.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#910 Allow changing default allowed restart count
  clusterloader2/pkg/measurement/common/system_pod_metrics.go
  clusterloader2/pkg/measurement/common/system_pod_metrics_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#911 Decrease verbosity of Prometheus firewall rule checking
  run-e2e-with-prometheus-fw-rule.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
