Repository kubernetes/perf-tests, pull requests merged in 2019-05, with the labels that each got.

#525 Switch to apps/v1
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
  dns/cluster/coredns-deployment.yaml
  dns/cluster/kube-dns-deployment.yaml
  perfdash/deployment.yaml
  slo-monitor/slo-monitor-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#526 Gather etcd metrics to prometheus
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#528 Prometheus: disable kube-proxy monitoring and scrape coredns every 10s
  clusterloader2/pkg/prometheus/manifests/default/kube-proxy-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorCoreDNS.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-serviceMonitorKubeProxy.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#529 Fix expected targets after #528
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#530 Release new slo-monitor image to gcr.io.
  slo-monitor/Makefile
  slo-monitor/slo-monitor-deployment.yaml
  slo-monitor/slo-monitor-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#531 Dashboard for watching master metrics.
  clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#532 Add mm4tt to clusterloader2 OWNERS.
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#518 Experimental snapshotting of Prometheus's PD (GCP only).
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/prometheus.go
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/M

#507 ClusterLoader - Fixing api responsiveness prometheus log
  clusterloader2/README.md
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#501 Perfdash - e2e metric fix
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#533 Update prometheus operator to v0.30.0
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#535 Upgrade prometheus and grafana to the newest versions
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#539 ClusterLoader - Adding 50th perc of resource usage
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#540 Perfdash - Label fix
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/script.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#538 Scrape etcd metrics via prometheus.
  clusterloader2/pkg/prometheus/manifests/default/master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/default/master-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/master-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
  clusterloader2/testing/prometheus/scrape-etcd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#541 failing-test: remove duplicate ports and endpoints
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-service.yaml
  clusterloader2/pkg/prometheus/manifests/kubemark/kubemark-master-serviceMonitor.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#543 Print config on startup
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#542 Make (stripped) prometheus work on gke.
  clusterloader2/pkg/prometheus/manifests/default/master-ip/README.md
  clusterloader2/pkg/prometheus/manifests/default/master-ip/master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/default/master-ip/master-service.yaml
  clusterloader2/pkg/prometheus/manifests/default/master-ip/master-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#545 Create logviewer/OWNERS
  logviewer/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#534 Migrate prometheus dashboards to separate files
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/network-programming-latency.json
  clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL
