Repository kubernetes/perf-tests, pull requests merged in 2019-01, with the labels that each got.

#361 Change apiserver's memory limit to 1200M.
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#350 ClusterLoader - Adding env flags
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/flags/flags.go
  clusterloader2/pkg/flags/types.go
  clusterloader2/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#362 ClusterLoader - Changing to 1 svc per 2 rcs
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/rc.yaml
  clusterloader2/testing/load/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#363 ClusterLoader - Updating density 100 nodes constraints
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#364 ClusterLoader - Adding multiple clients
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/framework/multiclient.go
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/simple/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/common/simple/scheduler_latency.go
  clusterloader2/pkg/measurement/common/simple/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/simple/wait_for_pods.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/test/simple_context.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#365 ClusterLoader - Adding ParallelismLimitedLoad tuning set
  clusterloader2/api/types.go
  clusterloader2/pkg/tuningset/parallelism_limited.go
  clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#366 ClusterLoader - Executing load test service operation in a sequence.
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#370 Add mborsz to perfdash/OWNERS
  perfdash/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#372 ClusterLoader - Changing to original load RC randimized range
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#373 Use os.MkdirAll instead of os.MkDir when creating report dir
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#374 ClusterLoader - Making every second RC use svc
  clusterloader2/testing/load/rc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#377 ClusterLoader - Separating test throughput
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#380 Revert "ClusterLoader - Changing to original load RC randimized range"
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#379 ClusterLoader - Adding override for kubemark 500
  clusterloader2/testing/load/kubemark/500_nodes/override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#382 ClusterLoader - Logging profile error for gke
  clusterloader2/pkg/measurement/common/simple/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#383 ClusterLoader - Bumping up controller manager memory
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#376 Clusterloader - Bumping up scheduler memory constraint
  clusterloader2/testing/density/100_nodes/constraints.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#386 ClusterLoader - Adding timeout status for controlling objects checkers
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#387 ClusterLoader - Adding high density override
  clusterloader2/testing/density/600_nodes/high_density_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#388 ClusterLoader - Fixing wait for controlling objects timeout
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#389 Adding myself to OWNERS
  dns/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#393 ClusterLoader - log which ReplicationControllers have timed-out.
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#392 ClusterLoader - Increasing timeout for waiting for deletion operations
  clusterloader2/pkg/measurement/common/simple/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Labels: approved, cncf-cla: yes, lgtm, size/M
