Repository kubernetes/perf-tests, pull requests merged in 2020-06, with the labels that each got.

#1298 ClusterLoader2: use verbosity to customize measurement logging
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/wait_for_nodes.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
  clusterloader2/pkg/measurement/common/wait_for_pvcs.go
  clusterloader2/pkg/measurement/common/wait_for_pvs.go
  clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go
  clusterloader2/pkg/measurement/util/phase_latency.go
  clusterloader2/pkg/measurement/util/wait_for_nodes.go
  clusterloader2/pkg/measurement/util/wait_for_pods.go
  clusterloader2/pkg/measurement/util/wait_for_pvcs.go
  clusterloader2/pkg/measurement/util/wait_for_pvs.go
  clusterloader2/pkg/util/cluster.go
  clusterloader2/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1295 clusterloader2: add "--from-from-cluster" flag to support in-cluster client config if "--kubeconfig" is empty
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/framework/config/client_config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1294 Cleanup old overrides
  clusterloader2/testing/density/2000_nodes/override.yaml
  clusterloader2/testing/density/5000_nodes/override.yaml
  clusterloader2/testing/density/600_nodes/high_density_override.yaml
  clusterloader2/testing/load/gce/throughput_override.yaml
  clusterloader2/testing/load/kubemark/500_nodes/override.yaml
  clusterloader2/testing/load/kubemark/throughput_override.yaml
  clusterloader2/testing/node-throughput/containerd_override.yaml
  clusterloader2/testing/node-throughput/docker_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1305 ClusterLoader: remove PrintVerboseLogs flags and use V levels
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1306 a misspelling
  clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1308 Add modifier to overwrite test configuration by flags
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/modifier/modifier.go
  clusterloader2/pkg/modifier/modifier_test.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1310 [CL2][Modifier][Overwrite] Fix 'int setting' and style issues
  clusterloader2/pkg/modifier/modifier.go
  clusterloader2/pkg/modifier/modifier_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1313 Fix wrong condition check
  clusterloader2/pkg/measurement/common/scheduler_latency.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1316 clusterloader2: Make sure the latency is not a negtive value
  clusterloader2/pkg/measurement/util/phase_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1309 Add cluster OOMs tracking in clusterloader2
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1321 MasterAndNonDaemons mode for resource gatherer (1.18)
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1324 Migrate to master and non-daemons mode (1.18)
  clusterloader2/testing/density/2000_nodes/override.yaml
  clusterloader2/testing/density/5000_nodes/override.yaml
  clusterloader2/testing/density/legacy/2000_nodes/override.yaml
  clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1323 MasterAndNonDaemons mode for resource gatherer (1.16)
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1322 MasterAndNonDaemons mode for resource gatherer (1.17)
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1329 Backport #1309: Add cluster OOMs tracking in clusterloader2 (1.15)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/overrides/enable_oom_tracking.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1326 Backport #1309: Add cluster OOMs tracking in clusterloader2 (1.18)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1328 Backport #1309: Add cluster OOMs tracking in clusterloader2 (1.16)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/overrides/enable_oom_tracking.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1327 Backport #1309: Add cluster OOMs tracking in clusterloader2 (1.17)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/overrides/enable_oom_tracking.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1333 Migrate to master and non-daemons mode (1.17)
  clusterloader2/testing/density/2000_nodes/override.yaml
  clusterloader2/testing/density/5000_nodes/override.yaml
  clusterloader2/testing/density/legacy/2000_nodes/override.yaml
  clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1334 Migrate to master and non-daemons mode (1.16)
  clusterloader2/testing/density/2000_nodes/override.yaml
  clusterloader2/testing/density/5000_nodes/override.yaml
  clusterloader2/testing/density/legacy/2000_nodes/override.yaml
  clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1336 Fix OOMs tracking var name in configs
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1335 Fix OOMs tracking var name in configs
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1337 Fix OOMs tracking var name in configs
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1340 Add a note about Kubemark in OOMs detection doc
  clusterloader2/docs/oom_detection.md
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1342 Exec command in the middle of performance test.
  clusterloader2/pkg/measurement/common/exec.go
  clusterloader2/pkg/util/util.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1345 Allow load tests to run with hostNetwork pods
  clusterloader2/cmd/clusterloader.go
  clusterloader2/testing/load/daemonset.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/job.yaml
  clusterloader2/testing/load/simple-deployment.yaml
  clusterloader2/testing/load/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1341 Cherry-pick --skip-steps from master
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/modifier/modifier.go
  clusterloader2/pkg/modifier/modifier_test.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1346 Do not track OOMs happening before test start in clusterloader2
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1317 remove metrics reset. Use get to obtain initial metrics values
  clusterloader2/pkg/measurement/common/scheduler_latency.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1348 Add ignore mechanism for specified processes to OOM tracking
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1350 OOM tracking: backport #1348, #1346 and #1340 (release-1.18)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1351 OOM tracking: backport #1348, #1346 and #1340 (release-1.17)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1352 OOM tracking: backport #1348, #1346 and #1340 (release-1.16)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1353 OOM tracking: backport #1348, #1346 and #1340 (release-1.15)
  clusterloader2/docs/oom_detection.md
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1355 Backport: probers: log to file
  clusterloader2/pkg/measurement/common/probes/manifests/dnsLookup/dns-prober-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/ping-server-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1356 [1.18] Backport Exec measurement from master
  clusterloader2/pkg/measurement/common/exec.go
  clusterloader2/pkg/util/util.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
