Repository kubernetes/perf-tests, pull requests merged in 2020-03, with the labels that each got.

#1090 Use 30s as the threshold for cluster-scoped list calls (1.15)
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1084 clusterloader2: collect scheduling_algorithm_duration_seconds to see algorithm latency without binding
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/vendor/k8s.io/kubernetes/pkg/scheduler/metrics/metrics.go
  clusterloader2/vendor/vendor.json
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1094 Update perfdash to 2.20.
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1091 Use 30s as the threshold for cluster-scoped list calls (1.14)
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1093 [Remove density] Rework SchedulingThroughput
  clusterloader2/pkg/measurement/common/scheduling_throughput.go
  clusterloader2/testing/load/experimental-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1098 perfdash: add deploy target to Makefile.
  perfdash/Makefile
  perfdash/deploy.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1100 Disable Go modules in perfdash make targets.
  perfdash/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1097 [Access-tokens] Backport test and dependencies from 'master'
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/pkg/measurement/common/simple/sleep.go
  clusterloader2/pkg/prometheus/manifests/dashboards/__init__.py
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/testing/access-tokens/config.yaml
  clusterloader2/testing/access-tokens/deployment.yaml
  clusterloader2/testing/access-tokens/role.yaml
  clusterloader2/testing/access-tokens/roleBinding.yaml
  clusterloader2/testing/access-tokens/serviceAccount.yaml
  clusterloader2/testing/access-tokens/token.yaml
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1102 Disable Go Modules in scripts used by travis (and pre-push hook)
  _hook/pre-push
  verify/test.sh
  verify/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1106 Fix confusing log line in exposeAPIServerMetrics
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1105 [Access-tokens] Backport test and dependencies from 'master'
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/pkg/measurement/common/simple/sleep.go
  clusterloader2/pkg/prometheus/manifests/dashboards/__init__.py
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/testing/access-tokens/config.yaml
  clusterloader2/testing/access-tokens/deployment.yaml
  clusterloader2/testing/access-tokens/role.yaml
  clusterloader2/testing/access-tokens/roleBinding.yaml
  clusterloader2/testing/access-tokens/serviceAccount.yaml
  clusterloader2/testing/access-tokens/token.yaml
  verify/verify-flags/known-flags.txt
Labels: approved, cncf-cla: yes, lgtm, size/L

#1107 [NodeKiller] Change rounding of a number of selected nodes
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1088 perfdash: display metrics from ci-benchmark-scheduler-perf-master
  perfdash/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1111 Fix to handle exec_service error + not starting service creation latency measurment when --enable-exec-service flag is disabled
  clusterloader2/pkg/measurement/common/service_creation_latency.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1113 [NodeKiller] Add override to ignore expected crashes
  clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1114 Bump perfdash to 2.21
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1108 Add dns test that simulates searchpath expansion.
  dns/README.md
  dns/params/coredns/default.yaml
  dns/params/kubedns/default.yaml
  dns/params/nodelocaldns/default.yaml
  dns/queries/all-queries.txt
  dns/queries/outside.txt
  dns/run
Labels: approved, cncf-cla: yes, lgtm, size/M

#1115 Adding changes to fetch an object of type map from config params
  clusterloader2/pkg/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1109 [NodeKiller] Schedule reboot and disconnect from node
  clusterloader2/pkg/chaos/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1116 [NodeKiller] Add override to ignore expected crashes
  clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1117 [NodeKiller] Add override to ignore expected crashes
  clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1119 [NodeKiller] Add override to ignore expected crashes
  clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1118 [NodeKiller] Add summary
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1120 Cherry-pick NodeKiller changes
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1121 Cherry-pick NodeKiller changes
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1122 Cherry-pick NodeKiller changes
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1126 Add CL2 prefix to ENABLE_PVS variable, to allow value to be overriden using env variable
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/experimental-config.yaml
  clusterloader2/testing/load/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1124 Add measurement to collect windows node cpu usage per process
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
  clusterloader2/pkg/prometheus/gce_windows_util.go
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-windows-scrape-configs.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/node-throughput/config.yaml
  clusterloader2/testing/node-throughput/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1128 prefixing ENABLE_NETWORKPOLICIES with CL2_ for consistency
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1132 Expand the scraping timeout
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
  clusterloader2/pkg/prometheus/manifests/prometheus-windows-scrape-configs.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1135 [NodeKiller] Rebooting broken nodes before exiting the test
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1140 Revert "[NodeKiller] Schedule reboot and disconnect from node"
  clusterloader2/pkg/chaos/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1145 Unpack the string values from the CL2_.* envs
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/config/template_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1141 Fix a typo
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1127 clusterloader2: improve experience on aks
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/measurement/common/etcd_metrics.go
  clusterloader2/pkg/measurement/common/profile.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1125 Set the extended load test override defaults to true
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/experimental-config.yaml
  clusterloader2/testing/load/statefulset.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1144 Add missing CL2 prefix to override variables
  clusterloader2/testing/load/experimental/overrides/enable_configmaps.yaml
  clusterloader2/testing/load/experimental/overrides/enable_daemonsets.yaml
  clusterloader2/testing/load/experimental/overrides/enable_jobs.yaml
  clusterloader2/testing/load/experimental/overrides/enable_networkpolicies.yaml
  clusterloader2/testing/load/experimental/overrides/enable_pvs.yaml
  clusterloader2/testing/load/experimental/overrides/enable_secrets.yaml
  clusterloader2/testing/load/experimental/overrides/enable_statefulsets.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1136 CL2: fix etcd profiles gathering
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/measurement/common/profile.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1143 Add load test for iis container
  clusterloader2/pkg/prometheus/gce_windows_util.go
  clusterloader2/pkg/prometheus/manifests/prometheus-windows-scrape-configs.yaml
  clusterloader2/testing/node-throughput/windows_override.yaml
  clusterloader2/testing/windows-tests/OWNERS
  clusterloader2/testing/windows-tests/config.yaml
  clusterloader2/testing/windows-tests/rc.yaml
  clusterloader2/testing/windows-tests/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
