Repository kubernetes/perf-tests, pull requests merged in 2020-07, with the labels that each got.

#1344 consolidate provider related logic into a single place
  clusterloader2/pkg/provider/aks.go
  clusterloader2/pkg/provider/aws.go
  clusterloader2/pkg/provider/constants.go
  clusterloader2/pkg/provider/eks.go
  clusterloader2/pkg/provider/gce.go
  clusterloader2/pkg/provider/gke.go
  clusterloader2/pkg/provider/kubemark.go
  clusterloader2/pkg/provider/local.go
  clusterloader2/pkg/provider/provider.go
  clusterloader2/pkg/provider/skeleton.go
  clusterloader2/pkg/provider/util.go
  clusterloader2/pkg/provider/vsphere.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#1359 MasterAndNonDaemons mode for resource gatherer (1.15)
  clusterloader2/pkg/measurement/common/simple/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1360 Migrate to master and non-daemons mode (1.15)
  clusterloader2/testing/density/2000_nodes/override.yaml
  clusterloader2/testing/density/5000_nodes/override.yaml
  clusterloader2/testing/density/legacy/2000_nodes/override.yaml
  clusterloader2/testing/density/legacy/5000_nodes/override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1364 Fix wrong type in Errorf format (1.18)
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1365 Fix wrong type in Errorf format (1.17)
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1366 Fix wrong type in Errorf format (1.16)
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1362 Specify namespace in ResourceUsageSummary measurement
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1367 Add webhook addmission duration panel to Grafana
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#1369 Slow API calls - backport #1262, #1258, #1213, #1229 and #1209 (release-1.18)
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XL

#1368 Remove duplicate OOM event reports in OOM tracker
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1370 Slow API calls - backport #1262, #1258, #1213, #1229, #1209, #915, #923 and #914 (release-1.17)
  clusterloader2/pkg/measurement/common/slos/api_responsiveness.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XXL

#1374 * Added support for GitHub bearer token
  perfdash/github-configs-fetcher.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1376 Remove duplicate OOM event reports in OOM tracker (1.17)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1378 Remove duplicate OOM event reports in OOM tracker (1.15)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1375 Remove duplicate OOM event reports in OOM tracker (1.18)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1377 Remove duplicate OOM event reports in OOM tracker (1.16)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1131 Add ipv6 support for network performance test
  network/benchmarks/netperf/nptest/nptest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1382 Refactor perfdash codebase for future S3 support
  perfdash/Makefile
  perfdash/metrics-downloader-helper.go
  perfdash/metrics-downloader.go
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1391 Cl2 env template params - backport #1263, #1145, #998 & #921 (release-1.17)
  clusterloader2/README.md
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/config/template_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1392 Cl2 env template params - backport #1263, #1145, #998 & #921 (release-1.16)
  clusterloader2/README.md
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/config/template_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1393 Cherry-pick CL2_* env template params fixes to release-1.18
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/config/template_provider_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1394 Enable slow API calls allowance in 1.17 tests
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1385 Use gofmt to fix lint issues and update perfdash README
  perfdash/README.md
  perfdash/metrics-downloader.go
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1372 Update etcd_disk_backend_commit_duration_seconds histogram to etcd_disk_backend_commit_duration_seconds_bucket
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1398 Regenerate master dashboard
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1358 use provider across clusterloader2.
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/measurement/common/etcd_metrics.go
  clusterloader2/pkg/measurement/common/metrics_for_e2e.go
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/measurement/common/profile.go
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go
  clusterloader2/pkg/measurement/util/kubemark/kubemark.go
  clusterloader2/pkg/measurement/util/ssh.go
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/gce_windows_util.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1401 Make schedulerThroughput measurement SLO violation failing a test customizable
  clusterloader2/pkg/measurement/common/scheduling_throughput.go
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/S

#1403 Make schedulerThroughput measurement SLO violation failing a test customizable (release-1.18)
  clusterloader2/pkg/measurement/common/scheduling_throughput.go
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/S

#1402 Make schedulerThroughput measurement SLO violation failing a test customizable (release-1.19)
  clusterloader2/pkg/measurement/common/scheduling_throughput.go
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/S

#1404 Fix errors from linter in release-1.19
  perfdash/metrics-downloader.go
  perfdash/perfdash.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1400 Set the verbosity level in the info logs
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/measurement/common/etcd_metrics.go
  clusterloader2/pkg/measurement/common/exec.go
  clusterloader2/pkg/measurement/common/ooms_tracker.go
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/measurement/common/profile.go
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/measurement/common/scheduling_throughput.go
  clusterloader2/pkg/measurement/common/service_creation_latency.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
  clusterloader2/pkg/measurement/common/system_pod_metrics.go
  clusterloader2/pkg/measurement/common/timer.go
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/measurement/util/phase_latency.go
  clusterloader2/pkg/measurement/util/prometheus.go
  clusterloader2/pkg/measurement/util/wait_for_pods.go
  clusterloader2/pkg/modifier/modifier.go
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/gce_windows_util.go
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/prometheus/util.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1405 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1396 Add AWS S3 functionality for perfdash
  perfdash/Makefile
  perfdash/gcs_metrics_bucket.go
  perfdash/go.mod
  perfdash/go.sum
  perfdash/metrics-downloader.go
  perfdash/perfdash.go
  perfdash/s3_metrics_bucket.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1408 fix typos
  clusterloader2/docs/design.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
