Repository kubernetes/perf-tests, pull requests merged in 2020-09, with the labels that each got.

#1445 chore: remove travis ci badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1426 feat: Add errcheck linter with golangci-lint
  .golangci.yml
  benchmark/pkg/comparer/comparer.go
  benchmark/pkg/metricsfetcher/runselector/selector.go
  benchmark/pkg/metricsfetcher/util/mock_util.go
  benchmark/pkg/metricsfetcher/util/util.go
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/measurement/common/service_creation_latency.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/provider/util.go
  clusterloader2/pkg/tuningset/global_qps_load.go
  network/benchmarks/netperf/launch.go
  network/benchmarks/netperf/nptest/nptest.go
  perfdash/metrics-downloader-helper.go
  perfdash/metrics-downloader.go
  perfdash/perfdash.go
  slo-monitor/src/monitors/store.go
  slo-monitor/src/monitors/watcher.go
  util-images/access-tokens/cmd/main.go
  util-images/probes/pkg/ping/server/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1446 feat: add deadcode linter in golangci-lint
  .golangci.yml
  compare/src/compare-resources.go
  network/benchmarks/netperf/launch.go
  perfdash/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1448 feat: enable govet in golangci-lint
  .golangci.yml
  clusterloader2/api/types.go
  clusterloader2/pkg/measurement/util/resource.go
  clusterloader2/pkg/prometheus/util.go
  slo-monitor/src/monitors/store.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1447 feat: migrate benchmark package to golang modules
  benchmark/Godeps/Godeps.json
  benchmark/Godeps/Readme
  benchmark/go.mod
  benchmark/go.sum
  benchmark/vendor/github.com/aclements/go-moremath/mathx/package.go
  benchmark/vendor/github.com/dgryski/go-onlinestats/dea.go
  benchmark/vendor/github.com/dgryski/go-onlinestats/stats.go
  benchmark/vendor/github.com/dgryski/go-onlinestats/utest.go
  benchmark/vendor/github.com/golang/glog/README
  benchmark/vendor/github.com/golang/glog/glog.go
  benchmark/vendor/github.com/spf13/pflag/.gitignore
  benchmark/vendor/github.com/spf13/pflag/.travis.yml
  benchmark/vendor/github.com/spf13/pflag/README.md
  benchmark/vendor/github.com/spf13/pflag/bool_slice.go
  benchmark/vendor/github.com/spf13/pflag/bytes.go
  benchmark/vendor/github.com/spf13/pflag/count.go
  benchmark/vendor/github.com/spf13/pflag/duration_slice.go
  benchmark/vendor/github.com/spf13/pflag/flag.go
  benchmark/vendor/github.com/spf13/pflag/golangflag.go
  benchmark/vendor/github.com/spf13/pflag/int16.go
  benchmark/vendor/github.com/spf13/pflag/ip.go
  benchmark/vendor/github.com/spf13/pflag/ip_slice.go
  benchmark/vendor/github.com/spf13/pflag/ipnet.go
  benchmark/vendor/github.com/spf13/pflag/string_array.go
  benchmark/vendor/github.com/spf13/pflag/string_slice.go
  benchmark/vendor/github.com/spf13/pflag/uint_slice.go
  benchmark/vendor/k8s.io/kubernetes/test/e2e/perftype/BUILD
  benchmark/vendor/modules.txt
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#1449 Increase page size in slo-monitor to 5000 (attempt #2).
  slo-monitor/Makefile
  slo-monitor/src/monitors/pod_monitor.go
  slo-monitor/src/monitors/watcher.go
  slo-monitor/src/third_party/forked/k8s.io/client-go/tools/cache/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1450 Exclude proxy subresource from API responsiveness
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1452 Use kubernetes.io/os after graduation from beta
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1451 Fix benchmark Makefile after migration to go modules
  benchmark/Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#1456 feat: add github issue and pull requests templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#1457 Pin python and pip to v2 version
  dns/run
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1442 perfdash: add scheduler throughput/latency labels
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1467 cl2/density: make MIN_LATENCY_PODS configurable
  clusterloader2/testing/density/config.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#1464 cl2/density: add pod affinty, pod topology spreading workloads to scheduler suite
  clusterloader2/testing/density/scheduler-suite.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, sig/scheduling, sig/testing, size/L

#1472 Generate names for unnamed steps in clusterloader2
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/scalability, size/S

#1473 Bump timeout for the linter test job
  .golangci.yml
  verify/verify-lint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1436 Add per step reporting in CL2
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_reporter.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/L

#1478 Append ordinal numbers to test steps names
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1477 Fix memory usage when listing pods/events
  slo-monitor/Makefile
  slo-monitor/src/monitors/pod_monitor.go
  slo-monitor/src/monitors/watcher.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1474 perfdash: add pod-affinity, pod-topology-spread workloads
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, sig/scheduling, size/S

#1480 Slo-monitor cleanup
  slo-monitor/Makefile
  slo-monitor/src/monitors/watcher.go
  slo-monitor/src/third_party/forked/k8s.io/client-go/tools/cache/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1475 Introduce SchedulerInsecurePortDisabled
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/provider/provider.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1443 Allow per-job path override for clusterloader2 results dir
  perfdash/config.go
  perfdash/metrics-downloader.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1486 Prepend step names with ordinal tags
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1490 Rename PodStartupLatency to CreatePhasePodStartupLatency in load test
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1485 Add density test to load test
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#1493 Better perf-tests reporting - backport to release-1.18
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_reporter.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1495 Better perf-tests reporting - backport to release-1.16
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_reporter.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1494 Better perf-tests reporting - backport to release-1.17
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_reporter.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1492 Better perf-tests reporting - backport to release-1.19
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_reporter.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1499 Add SchedulingThroughput and SchedulingLatency in load test to perf-dash
  perfdash/config.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1479 Combined SLO measurement- initial commit
  clusterloader2/pkg/measurement/common/slos/slo_measurement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1501 Bump perfdash version to 2.28
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1503 Move prometheus measurement to common package
  clusterloader2/pkg/measurement/common/prometheus_measurement.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/network_programming_test.go
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1504 Add Python specific test suite to allow migration to Python3
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#1470 Migrate dns benchmarks from python2 to python3
  clusterloader2/pkg/prometheus/manifests/dashboards/__init__.py
  clusterloader2/pkg/prometheus/manifests/dashboards/defaults.py
  clusterloader2/pkg/prometheus/manifests/dashboards/dns.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/network.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/slo.dashboard.py
  dns/py/data.py
  dns/py/data_test.py
  dns/py/ingest.py
  dns/py/params.py
  dns/py/params_test.py
  dns/py/run_perf.py
  dns/py/runner.py
  dns/run
  verify/boilerplate/boilerplate.py
  verify/boilerplate/boilerplate.py.txt
  verify/verify-flags-underscore.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1508 Fix cpu requests in load test when density test is enabled.
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1507 Mark 'verify-all' as deprecated, but leave it to make pass existing PRs
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1511 Add mborsz to perfdash/OWNERS
  perfdash/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS
