Repository kubernetes/perf-tests, pull requests merged in 2020-04, with the labels that each got.

#1138 Decouple SSH command execution in util.SSH to enable unit testing
  .gitignore
  clusterloader2/pkg/chaos/nodes.go
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1150 Clean up windows test configs from node-throughput test
  clusterloader2/testing/node-throughput/config.yaml
  clusterloader2/testing/node-throughput/rc.yaml
  clusterloader2/testing/node-throughput/windows_override.yaml
  clusterloader2/testing/windows-tests/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#1151 Delete Redundant "extended load test" override files
  clusterloader2/testing/load/experimental/overrides/enable_configmaps.yaml
  clusterloader2/testing/load/experimental/overrides/enable_daemonsets.yaml
  clusterloader2/testing/load/experimental/overrides/enable_jobs.yaml
  clusterloader2/testing/load/experimental/overrides/enable_networkpolicies.yaml
  clusterloader2/testing/load/experimental/overrides/enable_pvs.yaml
  clusterloader2/testing/load/experimental/overrides/enable_secrets.yaml
  clusterloader2/testing/load/experimental/overrides/enable_statefulsets.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1149 [NodeKiller][Config] Add known components to node killer expected crashes
  clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1082 clusterloader2: more info to TestMetrics action execute error logs
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1155 Fixing comment with clusterloader2/pkg/util/ssh.go Exec method to make it compliant with golint
  clusterloader2/pkg/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1154 Improve perfdash container build
  perfdash/Dockerfile
  perfdash/Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1152 Follow up from 1056
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/measurement/common/etcd_metrics.go
  clusterloader2/pkg/measurement/common/profile.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1156 cleanup the clusterloader2 load testing config file and deployment yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1081 clusterloader2: display extension points metrics
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/vendor/k8s.io/component-base/metrics/testutil/metrics.go
  clusterloader2/vendor/vendor.json
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1159 Return multiple summaries in Gather method
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/network_programming_test.go
  clusterloader2/pkg/measurement/common/slos/prometheus_measurement.go
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1158 Add windows memory usage measurement
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1160 Bump perfdash to 2.22
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1075 Perf tests 794- Create Wrapper measurement.
  clusterloader2/api/types.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/measurement/measurement_executor.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1167 ClusterLoader - fix provider check that is always true
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1168 ClusterLoader - add kubelet port override option
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/measurement/util/gatherers/resource_gather_worker.go
  clusterloader2/pkg/measurement/util/kubelet/kubelet.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1170 clusterloader: add a new flag delete-automanaged-namespaces
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1174 Remove namespace field from perfdash deployment
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1176 ClusterLoader: copy unexported legacy function
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/util/cluster.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1175 [ClusterLoader2] Enable custom timeouts for probes
  clusterloader2/pkg/measurement/common/probes/probes.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1177 Add configurable timeout for probes in configs
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1172 clusterloader2: drop metrics deprecated in 1.19
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1179 Bump perf-dash to 2.23
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1173 clusterloader: enhance namespace configurations
  clusterloader2/api/default.go
  clusterloader2/api/types.go
  clusterloader2/api/validation.go
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/flags/flags.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
  clusterloader2/testing/access-tokens/config.yaml
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/high-density-config.yaml
  clusterloader2/testing/density/legacy/config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/l4ilb/config.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental-config.yaml
  clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml
  clusterloader2/testing/load/legacy/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1178 Pass proper GCP project with snapshots storage to PrometheusController
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/scalability, size/S

#1180 ClusterLoader: update README
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1184 Changed perfdash service type to NodePort
  perfdash/perfdash-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1190 formatting changes probes.go
  clusterloader2/pkg/measurement/common/probes/probes.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1185 Change query function to rate for etcd_network_client_grpc_sent_bytes_total metric
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1186 Update instruction for deploy perf-dash
  perfdash/Makefile
  perfdash/README.md
  perfdash/deploy.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1183 Cleanup clusterloader2 load testing experimental config file
  clusterloader2/testing/load/experimental-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1192 Remove outdated experimental configs
  clusterloader2/testing/load/experimental/bundled_services_and_deployments.yaml
  clusterloader2/testing/load/legacy/config.yaml
  clusterloader2/testing/load/legacy/kubemark/500_nodes/override.yaml
  clusterloader2/testing/load/legacy/rc.yaml
  clusterloader2/testing/load/legacy/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1189 Create a script for building Kubernetes using golang tip
  golang/Makefile
  golang/build-go.sh
  golang/build-kubernetes.sh
  golang/push.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1146 Extend load test to immutable secrets/configmaps
  clusterloader2/testing/load/configmap.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1193 Set --private-bucket for pushing golang builds
  golang/push.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1194 Add CL2_ prefix to LOAD_TEST_THROUGHPUT
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental-config.yaml
  clusterloader2/testing/load/gce/throughput_override.yaml
  clusterloader2/testing/load/kubemark/500_nodes/override.yaml
  clusterloader2/testing/load/kubemark/throughput_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1153 Add sctp support for network performance test
  network/benchmarks/netperf/Dockerfile
  network/benchmarks/netperf/launch.go
  network/benchmarks/netperf/nptest/nptest.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1188 Add aggregated graphs to master dashboard
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1199 Snapshot Prometheus disk after tearing Prometheus down
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/manifests/0ssd-storage-class.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/M
