Repository kubernetes/perf-tests, pull requests merged in 2020-01, with the labels that each got.

#964 Clean up Prometheus firewall rule after test
  run-e2e-with-prometheus-fw-rule.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#961 Don't filter apiserver metrics
  clusterloader2/pkg/measurement/common/metrics_for_e2e.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#962 Bump throughput in scalability node tests
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#965 Ability to add Prometheus port firewall rule
  run-e2e-with-prometheus-fw-rule.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#967 Reduce the pod count to pass the windows load test
  clusterloader2/testing/node-throughput/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#966 Implement WaitForNodes measurement
  clusterloader2/pkg/measurement/common/wait_for_nodes.go
  clusterloader2/pkg/measurement/util/object_store.go
  clusterloader2/pkg/measurement/util/wait_for_nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#968 Expose node-throughput tests in perfdash
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#969 Bump node throughput to 10pods/s
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#970 Revert "Bump node throughput to 10pods/s"
  clusterloader2/testing/node-throughput/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#971 Overwrite pod throughput in throughput tests
  clusterloader2/testing/node-throughput/containerd_override.yaml
  clusterloader2/testing/node-throughput/docker_override.yaml
  clusterloader2/testing/node-throughput/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#973 scale up windows load test
  clusterloader2/testing/node-throughput/config.yaml
  clusterloader2/testing/node-throughput/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#975 Decrease containerd throughput to 5
  clusterloader2/testing/node-throughput/containerd_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#976 scale down to pass the load test
  clusterloader2/testing/node-throughput/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#972 Script to remove old prometheus snapshots
  clusterloader2/clean-up-old-snapshots.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#977 Fix scraping kube-apiserver pprofs
  clusterloader2/pkg/measurement/common/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#979 Simplify logging in the isNodeConditionSetAsExpected
  clusterloader2/pkg/util/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#982 Fix gathering profiles for kube-apiserver.
  clusterloader2/pkg/measurement/common/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#987 Retry also 401 (Unauthorized) errors
  clusterloader2/pkg/framework/client/objects.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#989 Add pod binding and pod creations graphs.
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#992 Fix broken links
  clusterloader2/README.md
  clusterloader2/pkg/measurement/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#988 Slow down the speed of pods creation to 1 pod / 30s
  clusterloader2/testing/node-throughput/windows_override.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#994 [ClusterLoader2] change slice related Go template functions
  clusterloader2/pkg/config/template_functions.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#996 [Travis] Add support to skip some go build targets
  .travis.yml
  verify/go-build.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#995 Fix gathering apiserver profiles
  clusterloader2/pkg/measurement/common/profile.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#998 [ClusterLoader2] Add information about environment variables to readme
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/scalability, size/S

#999 Log response' body from a call to Prometheus (proxied by apiserver).
  clusterloader2/pkg/prometheus/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1001 Retry 409 resource-quotas errors in CL2
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/framework/client/objects_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1004 Precompute network programming latency percentailes by endpoint
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
