Repository kubernetes/perf-tests, pull requests merged in 2020-12, with the labels that each got.

#1623 Make run-e2e.sh print commit history
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1626 Clean unused permissions for prometheus
  clusterloader2/pkg/prometheus/manifests/prometheus-roleBindingSpecificNamespaces.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-roleSpecificNamespaces.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#1628 Measure pod startup for stateless pods
  clusterloader2/pkg/measurement/common/service_creation_latency.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/phase_latency.go
  clusterloader2/pkg/measurement/util/pods_metadata.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1629 Perfdash: expose stateless pod startup latency
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1593 Adding network performance measurement testcases. (util-image changes)
  util-images/network/netperfbenchmark/Dockerfile
  util-images/network/netperfbenchmark/Makefile
  util-images/network/netperfbenchmark/cmd/main.go
  util-images/network/netperfbenchmark/go.mod
  util-images/network/netperfbenchmark/pkg/worker/util.go
  util-images/network/netperfbenchmark/pkg/worker/worker.go
Labels: approved, cncf-cla: yes, kind/feature, kind/regression, lgtm, ok-to-test, size/XL

#1633 Bunch of cl2 no-op cleanups
  clusterloader2/api/extensions.go
  clusterloader2/pkg/config/codec.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1635 Allow to scrape node local dns pods
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorNodeLocalDNS.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#1637 Add documentation for scraping prometheus metrics
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#1634 ClusterLoader2 Module API
  clusterloader2/README.md
  clusterloader2/api/extensions.go
  clusterloader2/api/types.go
  clusterloader2/pkg/test/modules.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1638 CLEANUP: move preparing test namespaces to a separate method
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/S
