Repository kubernetes/perf-tests, pull requests merged in 2020-10, with the labels that each got.

#1518 Removing network programming latency from slo measurement
  clusterloader2/pkg/measurement/common/slos/slo_measurement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1512 Reimplement scheduling throughput to prometheus metric
  clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1510 Add scheduling throughput/latency for load test in perf dash and add …
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1513 [cherry pick 1.19] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/high-density-config.yaml
  clusterloader2/testing/density/scheduler-suite.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1514 [cherry pick 1.18] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/high-density-config.yaml
  clusterloader2/testing/density/scheduler-suite.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1506 Config changes to add SLOMeasurement- initial commit
  clusterloader2/pkg/measurement/common/slos/slo_measurement.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1520 Decouple deletion test throughput from load test throughput.
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1521 [Cherrypick 1.19] Decouple deletion test throughput from load test throughput.
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1522 [Cherrypick 1.18] Decouple deletion test throughput from load test throughput.
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1439 perfdash/parser.go: remove unused throughput fields
  perfdash/parser.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1523 New method of counting slow queries [1.19]
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1524 [1.18] Add custom thresholds mechanism in APIResponsivenessPrometheus measurement
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/golang/custom_api_call_thresholds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1525 New method of counting slow queries [1.18]
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1527 Turn on alerting in load test for pod latency and scheduling throughput
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1529 Add overrides and SchedulingThroughputPrometheus to SLOMeasurement
  clusterloader2/pkg/measurement/common/slos/slo_measurement.go
  clusterloader2/pkg/measurement/common/slos/slo_measurement_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#1532 storage/pod-startup: name all steps
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#1531 clusterloader2: -provider is required
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#1528 Force Delete Pods on Timeout Initial Commit
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1540 Density in load test backport to 1.19
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#1541 Density in load test backport to 1.18
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1544 Fix density in load
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1542 Add SchedulingThroughputPrometheus to perfdash
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1546 Update configmap in load test for preparation to DNS tests
  clusterloader2/testing/load/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1516 [cherry pick 1.17] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/scheduler-suite.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1545 perfdash: parse vanilla results correctly
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#1548 Cleanup prometheus responsiveness param and remove outdated experimental load config
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/high-density-config.yaml
  clusterloader2/testing/experiments/enable_prometheus_api_responsiveness.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/experimental-config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1517 [cherry pick 1.16] scheduler-suite: pod-affinity, pod-anti-affinity, pod-topology-spread
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/scheduler-suite.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/overrides.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/overrides.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1551 Enable restart count checking by default
  clusterloader2/testing/access-tokens/config.yaml
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1550 Enable OOM tracking by default
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1526 Run a DNS workload as part of load tests.
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
