Repository kubernetes/perf-tests, pull requests merged in 2020-11, with the labels that each got.

#1552 Backport scheduling throughput to 1.18
  clusterloader2/pkg/measurement/common/scheduling_throughput.go
  clusterloader2/testing/load/experimental-config.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1553 Allow to wait and exit after command execution
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1556 Add Golang job script printing Golang repo commit hash
  golang/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1557 Rename WAIT_AFTER_EXEC_DURATION to SLEEP_AFTER_EXEC_DURATION in load test
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#1561 Backport exit after exec to 1 18
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1560 Backport exit after exec to 1 19
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1559 Add OWNERS file to golang subdirectory
  golang/OWNERS
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1563 Replace references to old topology labels with the new ones
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1565 Parametrize latency pod cpu and memory requests in load test
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#1566 Revert "Replace references to old topology labels with the new ones"
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1568 Backport cpu memory templating to 1.18
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#1567 Backport cpu memory templating to 1.19
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#1549 Define resource tracking mode based on cluster size
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/testing/access-tokens/config.yaml
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/high-density-config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1569 Allow to disable APIResponsivenessPrometheusSimple violations
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1571 Backport to 1.18: Allow to disable APIResponsivenessPrometheusSimple violations
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1570 Backport to 1.19: Allow to disable APIResponsivenessPrometheusSimple violations
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XS

#1573 Cherrypick of #1526 into 1.19 - Adding a new DNS workload in load tests
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/configmap.yaml
  clusterloader2/testing/load/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1572 Cherrypick of #1526 into 1.18 - Adding a new DNS workload in load tests
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/configmap.yaml
  clusterloader2/testing/load/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1576 Move the sleep command to a separate step
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1580 Adapt the event message regex in the OOM tracker (release-1.19)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1581 Adapt the event message regex in the OOM tracker (release-1.18)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1583 Adapt the event message regex in the OOM tracker (release-1.17)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1584 Adapt the event message regex in the OOM tracker (release-1.16)
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1579 Adapt the event message regex in the OOM tracker
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1588 Add missing bash options to dns/run.sh
  dns/run
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1589 Remove density flags in load test
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#1587 Fix dns benchmark failing after python 2->3 migration
  dns/py/data.py
  dns/py/runner.py
Labels: approved, cncf-cla: yes, lgtm, size/S

#1598 PoC of infra for running ad-hoc scale tests
  adhoc/README.md
  adhoc/run-e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1603 Add mising x(execute) bit to the adhoc/run-e2e-test.sh
  adhoc/run-e2e-test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1604 Backport slow count improvements and fixes to 1.17
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/golang/custom_api_call_thresholds.yaml
Labels: approved, cncf-cla: yes, kind/bug, kind/feature, lgtm, ok-to-test, size/L

#1609 Add jkaniuk to clusterloader2 release-1.16 OWNERS
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1607 Add jkaniuk to clusterloader2 release-1.18 OWNERS
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1608 Add jkaniuk to clusterloader2 release-1.17 OWNERS
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1605 Add jkaniuk to clusterloader2 release-1.19 OWNERS
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1606 Add jkaniuk to clusterloader2 OWNERS
  clusterloader2/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1600 Fix slow count for api responsiveness for cluster list
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, needs-ok-to-test, size/XS

#1612 bugfix in imagepreload.go
  clusterloader2/pkg/imagepreload/imagepreload.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1616 Move the sleep command to a separate step (release-1.18)
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1615 Move the sleep command to a separate step (release-1.19)
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1602 Backport slow count fix to 1.18
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1601 Backport slow count fix to 1.19
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1618 Backport metrics violation for density in load 1.18
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#1617 Backport metrics violation for density in load 1.19
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#1622 Fix lack of printing of steps beginning/end in CL2 (release-1.16)
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1620 Fix lack of printing of steps beginning/end in CL2 (release-1.18)
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1621 Fix lack of printing of steps beginning/end in CL2 (release-1.17)
  clusterloader2/pkg/test/simple_test_executor.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1613 Fix exception when get kube stdout
  dns/py/runner.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1596 When kubectl exec dig, the dns perf client selector podname is not correct
  dns/py/runner.py
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M
