Repository kubernetes/perf-tests, pull requests merged in 2021-11, with the labels that each got.

#1932 Fix TestHistogramQuantile test
  clusterloader2/pkg/measurement/util/histogram.go
  clusterloader2/pkg/measurement/util/histogram_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1926 Make master ServiceMonitor respect PROMETHEUS_SCRAPE_KUBELETS
  clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#1933 Remove _logviewer
  _logviewer/.gitignore
  _logviewer/BUILD.bazel
  _logviewer/OWNERS
  _logviewer/README.md
  _logviewer/WORKSPACE
  _logviewer/example/BUILD.bazel
  _logviewer/example/README.md
  _logviewer/example/bin/BUILD.bazel
  _logviewer/example/bin/test.go
  _logviewer/example/protos/BUILD.bazel
  _logviewer/example/protos/test.proto
  _logviewer/example/protos2/BUILD.bazel
  _logviewer/example/protos2/test2.proto
  _logviewer/go.mod
  _logviewer/go.sum
  _logviewer/mixer-client/BUILD.bazel
  _logviewer/mixer-client/main.go
  _logviewer/mixer/BUILD.bazel
  _logviewer/mixer/main.go
  _logviewer/mixer/mixer_test.go
  _logviewer/mixer/request/BUILD.bazel
  _logviewer/mixer/request/request.proto
  _logviewer/worker/BUILD.bazel
  _logviewer/worker/gcsreader.go
  _logviewer/worker/main.go
  _logviewer/worker/parsing.go
  _logviewer/worker/parsing_test.go
  _logviewer/worker/work/BUILD.bazel
  _logviewer/worker/work/work.proto
  verify/lib/gopkg.sh
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#1929 Install pdcsi driver in gke scalability test
  clusterloader2/drivers/gcp-csi-driver-stable.yaml
  clusterloader2/run-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XXL, approved, kind/bug, ok-to-test

#1938 Implement prometheus snapshot for CSI
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/experimental_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1939 Fix CSI driver for kubemark
  clusterloader2/run-e2e.sh
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug

#1941 fix kubemark test install pdcsi driver
  clusterloader2/run-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, needs-ok-to-test, approved

#1943 Add configurable timeout for Prometheus stack
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/flags/flags.go
  clusterloader2/pkg/flags/types.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#1947 Add CL2_DS_SURGE
  clusterloader2/testing/load/daemonset.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1948 Add endTime to Gatherer interface
  clusterloader2/pkg/measurement/common/metrics_server_prometheus.go
  clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
  clusterloader2/pkg/measurement/common/prometheus_measurement.go
  clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/network_programming_test.go
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved, ok-to-test

#1949 Add promql executor for unit tests
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/measurement/common/executors/promql_executor.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/slos/testdata/above_slow_count_failure.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/below_slow_count_pass.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/cluster_list_slo_failure.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/get_slo_failure.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/mutating_slo_failure.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/namespace_list_slo_failure.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/rules.yml
  clusterloader2/pkg/measurement/common/slos/testdata/slo_pass.yaml
Labels: lgtm, cncf-cla: yes, size/XXL, kind/feature, approved, ok-to-test

#1950 Add go modules file to dns/jsonify.
  dns/jsonify/go.mod
  dns/jsonify/go.sum
  dns/jsonify/vendor/github.com/golang/glog/LICENSE
  dns/jsonify/vendor/github.com/golang/glog/README
  dns/jsonify/vendor/github.com/golang/glog/glog.go
  dns/jsonify/vendor/github.com/golang/glog/glog_file.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/LICENSE
  dns/jsonify/vendor/gopkg.in/yaml.v2/LICENSE.libyaml
  dns/jsonify/vendor/gopkg.in/yaml.v2/NOTICE
  dns/jsonify/vendor/gopkg.in/yaml.v2/README.md
  dns/jsonify/vendor/gopkg.in/yaml.v2/apic.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/decode.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/emitterc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/encode.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/go.mod
  dns/jsonify/vendor/gopkg.in/yaml.v2/parserc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/readerc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/resolve.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/scannerc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/sorter.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/writerc.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/yaml.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/yamlh.go
  dns/jsonify/vendor/gopkg.in/yaml.v2/yamlprivateh.go
  dns/jsonify/vendor/k8s.io/kubernetes/LICENSE
  dns/jsonify/vendor/k8s.io/kubernetes/test/e2e/perftype/BUILD
  dns/jsonify/vendor/k8s.io/kubernetes/test/e2e/perftype/perftype.go
  dns/jsonify/vendor/vendor.json
  dns/run
Labels: lgtm, cncf-cla: yes, size/XXL, approved, kind/cleanup

#1936 Add a new go-dnsclient for scale tests.
  dns/dnsperfgo/Dockerfile
  dns/dnsperfgo/Makefile
  dns/dnsperfgo/README.md
  dns/dnsperfgo/go.mod
  dns/dnsperfgo/go.sum
  dns/dnsperfgo/main.go
  dns/dnsperfgo/metrics.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved
