Repository kubernetes/perf-tests, pull requests merged in 2021-08, with the labels that each got.

#1865 Remove huge services multiple deployments flag
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/huge-services.yaml
  clusterloader2/testing/load/modules/scheduler-throughput.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#1867 Automate testing scalability of Metrics Server
  clusterloader2/pkg/prometheus/README.md
  clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/resourceConsumer.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/resourceConsumerHpa.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#1860 [perfdash]: Migrate Docker image to distrolesss
  perfdash/Dockerfile
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#1871 Add SIGINT handler to handle Prometheus snapshot
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug

#1868 Add name to a test steps
  clusterloader2/testing/node-throughput/config.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/cleanup, ok-to-test

#1877 Update API responsiveness SLO to exclude long-running calls
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1869 Add modules for L4 ILB creation latency tests
  clusterloader2/testing/l4ilb/config.yaml
  clusterloader2/testing/l4ilb/modules/measurements.yaml
  clusterloader2/testing/l4ilb/modules/services.yaml
  clusterloader2/testing/l4ilb/service.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test
