Repository kubernetes/perf-tests, pull requests merged in 2021-01, with the labels that each got.

#1648 Snapshot prometheus disk even if we failed to tear down prometheus
  clusterloader2/pkg/prometheus/prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1644 Add a new prometheus measurement for dns latency
  clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1647 clusterloader2: completely switch to secure port
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/prometheus/manifests/master-ip/master-endpoints.yaml
  clusterloader2/pkg/prometheus/manifests/master-ip/master-service.yaml
  clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
  clusterloader2/pkg/provider/util.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, size/S

#1650 Copy metrics_grabber code from k/k & grab metrics from secure port
  clusterloader2/go.sum
  clusterloader2/pkg/measurement/common/metrics/api_server_metrics.go
  clusterloader2/pkg/measurement/common/metrics/cluster_autoscaler_metrics.go
  clusterloader2/pkg/measurement/common/metrics/controller_manager_metrics.go
  clusterloader2/pkg/measurement/common/metrics/kubelet_metrics.go
  clusterloader2/pkg/measurement/common/metrics/metrics_grabber.go
  clusterloader2/pkg/measurement/common/metrics/scheduler_metrics.go
  clusterloader2/pkg/measurement/common/metrics_for_e2e.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/BUILD
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/api.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/e2e_metrics.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/interesting_metrics.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/latencies.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/framework/metrics/pod.go
  clusterloader2/vendor/k8s.io/kubernetes/test/e2e/perftype/perftype.go
  clusterloader2/vendor/modules.txt
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL

#1652 Use ClusterFirst dnsPolicy in workloads.
  clusterloader2/testing/load/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1655 [Golang] Fix hollow node pods busybox image pulls issue
  golang/build-kubernetes.sh
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1651 Add node local dns latency to load test
  clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1656 Add containerd util image
  util-images/containerd/Dockerfile
  util-images/containerd/Makefile
  util-images/containerd/README.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#1657 Fix measuring latency of nodelocaldns
  clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1640 Module for service creation/deletion
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/services.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1654 Use containerd in image preloader
  clusterloader2/pkg/imagepreload/manifests/daemonset.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/S

#1662 Add latency threshold to load test for node local dns measurement
  clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S

#1663 Change yaml.load() to safe_load()
  dns/py/data_test.py
  dns/py/ingest.py
  dns/py/params.py
  dns/py/params_test.py
  dns/py/runner.py
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#1664 Fix golint issue caused by typo
  clusterloader2/pkg/measurement/util/pods_metadata.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#1665 Update node-exporter to 1.0.1
  clusterloader2/pkg/prometheus/manifests/exporters/node-exporter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1658 Upgrade Prometheus to v2.24.0
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1666 Fix printing k8s.io/perf-tests repo history
  run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1670 Add custom thresholds param to simple APIResponsiveness measurement
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1671 Cherry-pick of #97843 and #98141 to golang job
  golang/build-kubernetes.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1675 [release-1.17] Custom thresholds param to APIResponsivenessSimple measurement
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1674 [release-1.18] Custom thresholds param to APIResponsivenessSimple measurement
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1668 Set name in services module
  clusterloader2/testing/load/modules/services.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1672 [release-1.20] Custom thresholds param to APIResponsivenessSimple measurement
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1673 [release-1.19] Custom thresholds param to APIResponsivenessSimple measurement
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1676 distributed-provisioning.md: report with test setup and results
  adhoc/log/distributed-provisioning.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/L

#1678 Dump instanceIDs for master nodes in clusterloader
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/metadata/metadata.go
  clusterloader2/pkg/provider/aks.go
  clusterloader2/pkg/provider/aws.go
  clusterloader2/pkg/provider/eks.go
  clusterloader2/pkg/provider/gce.go
  clusterloader2/pkg/provider/gke.go
  clusterloader2/pkg/provider/kubemark.go
  clusterloader2/pkg/provider/local.go
  clusterloader2/pkg/provider/provider.go
  clusterloader2/pkg/provider/skeleton.go
  clusterloader2/pkg/provider/vsphere.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1679 Enable exec service by default in clusterloader2
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1530 PVC creation test
  clusterloader2/pkg/measurement/common/wait_for_pvs.go
  clusterloader2/pkg/measurement/util/object_store.go
  clusterloader2/pkg/measurement/util/wait_for_pvs.go
  clusterloader2/testing/experimental/storage/pod-startup/README.md
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/pvc.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume_binding/override.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume_creation/override.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1660 Revamp API availability measurement
  clusterloader2/pkg/measurement/common/api_availability_measurement.go
  clusterloader2/pkg/measurement/common/api_availability_metrics.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1690 modify the error url of override
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/docs, size/XS

#1685 Update CL2 api to use slice of pointers
  clusterloader2/api/types.go
  clusterloader2/pkg/modifier/modifier.go
  clusterloader2/pkg/modifier/modifier_test.go
  clusterloader2/pkg/state/namespaces_state.go
  clusterloader2/pkg/test/modules.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/tuningset/interface.go
  clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#1686 API availability measurement revamp - backport to release-1.20
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/api_availability_measurement.go
  clusterloader2/pkg/measurement/common/api_availability_metrics.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1687 API availability measurement revamp - backport to release-1.19
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/api_availability_measurement.go
  clusterloader2/pkg/measurement/common/api_availability_metrics.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1688 API availability measurement revamp - backport to release-1.18
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/api_availability_measurement.go
  clusterloader2/pkg/measurement/common/api_availability_metrics.go
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L
