Repository kubernetes/perf-tests, pull requests merged in 2021-05, with the labels that each got.

#1796 Upgrade perfdash to 2.33
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1799 Revert "Upgrade perfdash to 2.33"
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1801 Add custom thresholds override for 5k Kubemark job
  clusterloader2/testing/overrides/kubemark_5000_nodes.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1802 Make ILB count configurable and increase default to 2.
  clusterloader2/testing/l4ilb/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1804 Fix tuning set for the ILB test
  clusterloader2/testing/l4ilb/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1785 add load test for L4 LB nodesync
  clusterloader2/pkg/measurement/common/loadbalancer_nodesync_latency.go
  clusterloader2/testing/l4lb/config.yaml
  clusterloader2/testing/l4lb/dep.yaml
  clusterloader2/testing/l4lb/service.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1803 Network Performance tc's: changes for fetching worker pod logs
  clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml
  util-images/network/netperfbenchmark/cmd/main.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/S

#1808 Bump netperfbenchmark to 0.2
  clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml
  util-images/network/netperfbenchmark/Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#1809 Ignore exec subresource in APIResponsivenessPrometheus
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1811 Dump generated test config to artifacts folder
  clusterloader2/cmd/clusterloader.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1794 Add scheduler-throughput module
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/scheduler-throughput.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#1791 Add reconcile-objects module
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/reconcile-objects.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XL

#1812 Make L4 latency measurement timeout configurable.
  clusterloader2/testing/l4ilb/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1813 Add huge-services module
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/huge-services.yaml
  clusterloader2/testing/load/modules/scheduler-throughput.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/M

#1814 Fix api responsiveness filter
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/XS

#1816 Change load test job to be more resilient
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/job.yaml
  clusterloader2/testing/load/modules/reconcile-objects.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
