Repository kubernetes/perf-tests, pull requests merged in 2021-09, with the labels that each got.

#1879 pod startup: pre-define generic ephemeral volume type
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/genericephemeralinline/deployment_with_inline.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/genericephemeralinline/override.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#1884 perf-dash: Also cap scale on Command on mac.
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/www/script.js
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1883 Add lock when calling pingCheckers's functions to guarantee consistency
  clusterloader2/pkg/measurement/common/service_creation_latency.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, ok-to-test

#1888 [backport 1.19] Use containerd in image preloader
  clusterloader2/pkg/imagepreload/manifests/daemonset.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1887 [backport 1.20] Use containerd in image preloader
  clusterloader2/pkg/imagepreload/manifests/daemonset.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#1886 Fix stateless pod startup reporting and create report for stateful pods too
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/pods_metadata.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1890 Set www/ permissions in perfdash.
  perfdash/Dockerfile
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1891 Expose stateful pod startup in perfdash
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/pods_metadata.go
  perfdash/config.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1892 Add CL2_LATENCY_POD_COUNT
  clusterloader2/testing/load/modules/pod-startup-latency.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1894 Increase image preload timeout to 15m
  clusterloader2/pkg/imagepreload/imagepreload.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1893 Allow customisation of number of endpoints for huge service
  clusterloader2/testing/load/config.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#1897 Remove old hacky cherry-picks from golang
  golang/build-kubernetes.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#1899 Updates E2E test images registry
  clusterloader2/pkg/execservice/manifest/exec_deployment.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/resourceConsumer.yaml
Labels: lgtm, cncf-cla: yes, size/XS, sig/testing, approved, kind/cleanup

#1901 Added provider for Autopilot
  clusterloader2/pkg/provider/autopilot.go
  clusterloader2/pkg/provider/constants.go
  clusterloader2/pkg/provider/provider.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#1902 Set delete throughput override to 14
  clusterloader2/testing/overrides/load_throughput.yaml
  clusterloader2/testing/overrides/load_throughput_pre_1_23.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#1904 Print type when there is a merge value conflict.
  clusterloader2/pkg/config/template_provider.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1903 Turn off image preloading for Autopilot
  clusterloader2/pkg/provider/autopilot.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
