Repository kubernetes/perf-tests, pull requests merged in 2021-02, with the labels that each got.

#1682 Adds Google Anet Metrics Scraper
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorAnet.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/prometheus/scrape-anet.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#1697 Bump cpu and memory requests in perfdash
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1539 Fix OOM tracker in clusters with large number of events
  clusterloader2/pkg/measurement/common/ooms_tracker.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1700 Add support for 'topology.kubernetes.io/zone' label
  clusterloader2/pkg/prometheus/experimental.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1703 Enable Anet scraping
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorAnet.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/prometheus/scrape-anet.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1702 Enable Anet scraping
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorAnet.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/prometheus/scrape-anet.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1699 Enable Google Anet scraping
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorAnet.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/prometheus/scrape-anet.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1704 Change defaultCheckProbesReadyTimeout to 15m
  clusterloader2/pkg/measurement/common/probes/probes.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1692 Customize enabling of immutable secrets and configmaps in CL2
  clusterloader2/testing/load/configmap.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/secret.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1701 Add CL2 kind provider
  clusterloader2/README.md
  clusterloader2/pkg/provider/constants.go
  clusterloader2/pkg/provider/kind.go
  clusterloader2/pkg/provider/provider.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#1705 Change default PROBE_MEASUREMENTS_CHECK_PROBES_READY_TIMEOUT to 15m
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1667 Make Cl2 tests to work in <100 node clusters
  clusterloader2/pkg/tuningset/randomized_time_limited.go
  clusterloader2/testing/density/config.yaml
  clusterloader2/testing/density/high-density-config.yaml
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, size/M

#1680 Extract module compilation from test execution
  clusterloader2/api/types.go
  clusterloader2/api/validation.go
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/config/template_provider_test.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#1707 Handle both old and new topology labels in perf-tests
  clusterloader2/pkg/provider/gce.go
  clusterloader2/pkg/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1710 Add a README entry about the APIAvailabilityMeasurement
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/XS

#1711 Revert "Merge pull request #1680 from lyzs90/extract-module-compilation"
  clusterloader2/api/types.go
  clusterloader2/api/validation.go
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/config/template_provider_test.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1714 Scratch image generation
  util-images/scratch/Dockerfile
  util-images/scratch/Makefile
  util-images/scratch/README.md
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/M

#1538 Add CL2_PROMETHEUS_SLOW_APISERVER
  clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/S

#1718 Fix keyFile assignment for AWS provider
  clusterloader2/pkg/measurement/util/ssh.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1645 Network performance measurement: Implementing worker using CRD
  util-images/network/netperfbenchmark/go.mod
  util-images/network/netperfbenchmark/pkg/worker/util.go
  util-images/network/netperfbenchmark/pkg/worker/worker.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/L

#1681 Add huge services to load test
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/simple-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1709 Load test - latency pod measurements moved to pod-startup-latency.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/pod-startup-latency.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#1725 Fix: only check label key in LegacyIsMasterNode
  clusterloader2/pkg/util/cluster.go
  clusterloader2/pkg/util/cluster_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#1729 Add a README entry about the APIAvailabilityMeasurement - release-1.20
  clusterloader2/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1728 Add huge services to load test - release-1.19
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/simple-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1730 test: update pause-win image to the new one k8s.gcr.io/pause:3.4.1
  clusterloader2/testing/windows-tests/config.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1727 Add huge services to load test - release-1.20
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/simple-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1708 Load test - services.yaml small refactor
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/services.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#1712 Revert #1711 and fix test suite overrides
  clusterloader2/api/types.go
  clusterloader2/api/validation.go
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_context.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#1735 Automated cherry pick of #1718: Fix keyFile assignment for AWS provider
  clusterloader2/pkg/measurement/util/ssh.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1736 Automated cherry pick of #1725: Fix: only check label key in LegacyIsMasterNode
  clusterloader2/pkg/util/cluster.go
  clusterloader2/pkg/util/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1737 Automated cherry pick of #1725: Fix: only check label key in LegacyIsMasterNode
  clusterloader2/pkg/util/cluster.go
  clusterloader2/pkg/util/cluster_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1740 Add option to change checkIfPodsAreUpdated
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#1739 Allow to disable daemonsets in load test
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#1743 Allow user-defined node taints in CL2
  clusterloader2/pkg/util/cluster.go
Labels: approved, cncf-cla: yes, lgtm, sig/scalability, size/M

#1694 CL2 config validation
  clusterloader2/api/default.go
  clusterloader2/api/types.go
  clusterloader2/api/validation.go
  clusterloader2/api/validation_test.go
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/test/test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XL

#1558 Add resource scope to api call latency to show anything
  clusterloader2/pkg/prometheus/manifests/dashboards/dns.json
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/network.json
  clusterloader2/pkg/prometheus/manifests/dashboards/requirements.txt
  clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#1744 Check for absolute path also while validating object files
  clusterloader2/api/validation.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1684 Add kube-state-metrics latency measurement
  clusterloader2/pkg/measurement/common/kube_state_metrics_measurement.go
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/measurement/summary.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#1733 Add more descriptive error for github downloading issues
  perfdash/github-configs-fetcher.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1749 Add P&F metrics to dashboard
  clusterloader2/pkg/prometheus/manifests/dashboards/dns.json
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/network.json
  clusterloader2/pkg/prometheus/manifests/dashboards/slo.json
Labels: approved, cncf-cla: yes, lgtm, size/XL
