Repository kubernetes/perf-tests, pull requests merged in 2021-12, with the labels that each got.

#1951 Add a CL2 parameter for creating headless huge services.
  clusterloader2/testing/load/modules/huge-services.yaml
  clusterloader2/testing/load/service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved, ok-to-test

#1952 Extend log entry for in progress WaitForControlledPodsRunning
  clusterloader2/go.mod
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/util/pods.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
  clusterloader2/pkg/measurement/util/wait_for_pods.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#1954 Revert "Customize enabling of immutable secrets and configmaps in CL2"
  clusterloader2/testing/load/configmap.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/secret.yaml
Labels: lgtm, cncf-cla: yes, size/S, sig/scalability, approved, kind/cleanup

#1900 perfdash: use NEG for kubernetes service
  perfdash/perfdash-service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, sig/scalability, approved, kind/cleanup, sig/k8s-infra

#1955 Add implementaion of Pushgateway feature
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/pushgateway/deployment.yaml
  clusterloader2/pkg/prometheus/manifests/pushgateway/service.yaml
  clusterloader2/pkg/prometheus/manifests/pushgateway/serviceMonitor.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#1956 Add separate huge service test config
  clusterloader2/testing/huge-service/config.yaml
  clusterloader2/testing/huge-service/modules/measurements.yaml
  clusterloader2/testing/huge-service/modules/service.yaml
  clusterloader2/testing/huge-service/service.yaml
  clusterloader2/testing/huge-service/simple-deployment.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#1957 Add generic Prometheus query measurement
  clusterloader2/examples/generic_query_example.yaml
  clusterloader2/pkg/measurement/common/generic_query_measurement.go
  clusterloader2/pkg/measurement/common/metrics_server_prometheus.go
  clusterloader2/pkg/measurement/common/nodelocaldns_latency_prometheus.go
  clusterloader2/pkg/measurement/common/prometheus_measurement.go
  clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/network_programming.go
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1958 Use metric name in summary
  clusterloader2/pkg/measurement/common/generic_query_measurement.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1960 Add Prometheus-based container restarts measurement
  clusterloader2/pkg/measurement/common/container_restarts.go
  clusterloader2/pkg/measurement/common/container_restarts_test.go
  clusterloader2/pkg/measurement/common/slos/testdata/container_restarts/double_restart_of_apiserver.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/container_restarts/no_restarts.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/container_restarts/two_apiserver_replicas_restarts.yaml
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, sig/scalability, size/L, kind/feature, approved

#1963 Added checkIfPodsAreUpdated param to CL2 scheduler-throughput and pod…
  clusterloader2/testing/load/modules/pod-startup-latency.yaml
  clusterloader2/testing/load/modules/scheduler-throughput.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved, ok-to-test
