Repository kubernetes/perf-tests, pull requests merged in 2021-04, with the labels that each got.

#1781 Update image name and cpu resources for network performance test worker image
  clusterloader2/pkg/measurement/common/network/manifests/worker-deployment.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/XS

#1780 Migrate NewInformer to cache.ListerWatcher
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/measurement/common/service_creation_latency.go
  clusterloader2/pkg/measurement/common/slos/pod_startup_latency.go
  clusterloader2/pkg/measurement/util/informer/informer.go
  clusterloader2/pkg/measurement/util/selector.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1777 Implement watch-based daemonset replica counter.
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/measurement/common/network/network_performance_measurement.go
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
  clusterloader2/pkg/measurement/util/runtimeobjects/replicaswatcher.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
  clusterloader2/pkg/measurement/util/wait_for_pods.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1782 Add parsers for common measurement matching any test name
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/metrics-downloader.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1783 Update prometheus-operator mem/cpu request/limits
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1784 Downgrade perf-dash to 2.32
  perfdash/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1786 Do not wait for inactive pods during scale down
  clusterloader2/pkg/measurement/util/wait_for_pods.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#1775 Delay the exec command step in the load test config
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1788 Reduce $totalSchedulerThroughputPods in large clusters
  clusterloader2/testing/load/config.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1787 Add measurements module
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/modules/measurements.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/L

#1793 Make prometheus-operator watch only limited set of secrets
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1795 Add marseel to sig-scalability-reviewers in perf-test repo
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS
