Repository kubernetes/perf-tests, pull requests merged in 2022-05, with the labels that each got.

#2050 Add container restarts and OOMs measurements to huge service test
  clusterloader2/testing/huge-service/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#2060 clusterloader2: error while calling prometheus api, part of the conte…
  clusterloader2/pkg/prometheus/util.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2057 stop using PSP API which is removed in 1.25
  clusterloader2/drivers/gcp-csi-driver-stable.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#2061 Enable Prometehus server for AKS provider
  clusterloader2/pkg/provider/aks.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved, ok-to-test

#2063 metrics-server test support kind and local provider
  clusterloader2/pkg/provider/kind.go
  clusterloader2/pkg/provider/local.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2069 Add konnectivity-agent to ignored restarts for node killer test
  clusterloader2/testing/chaosmonkey/ignore_node_killer_container_restarts_100.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2076 Add 'do not evict' annotation to Prometheus
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2077 Revert "Add 'do not evict' annotation to Prometheus"
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved
