Repository kubernetes/perf-tests, pull requests merged in 2022-12, with the labels that each got.

#2214 Reflect manually changed memory in deployment for perfdash
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2207 wait for services to be deleted
  clusterloader2/pkg/measurement/common/service_creation_latency.go
  clusterloader2/testing/l4lb/config.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved, ok-to-test

#2218 Set priorityclass in prometheus
  clusterloader2/pkg/prometheus/manifests/0prometheus-priorityclass.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2219 Improve error logging in exec service
  clusterloader2/pkg/measurement/common/api_availability_measurement.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2217 Update all OWNERS files and add tosi3k as reviewer
  OWNERS
  OWNERS_ALIASES
  benchmark/OWNERS
  clusterloader2/OWNERS
  dns/OWNERS
  perfdash/OWNERS
  slo-monitor/OWNERS
  util-images/probes/OWNERS
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#2220 Avoid race in subsequent changes to the same controller
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2222 Add timeout to exec command used for polling single master health
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/measurement/common/api_availability_measurement.go
  clusterloader2/pkg/measurement/common/service_creation_latency.go
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved, ok-to-test
