Repository kubernetes/perf-tests, pull requests merged in 2022-01, with the labels that each got.

#1967 Add enableViolations parameter to ContainerRestarts measurement params
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1966 Add measurement for cilium endpoint propagation delay
  clusterloader2/pkg/measurement/common/cilium_endpoint_propagation_delay.go
  clusterloader2/pkg/measurement/common/cilium_endpoint_propagation_delay_test.go
  clusterloader2/pkg/measurement/common/slos/testdata/cilium_endpoint_propagation_delay/default_slo_fail.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/cilium_endpoint_propagation_delay/default_slo_pass.yaml
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test

#1968 Install bind-tools in dnsperfgo image.
  dns/dnsperfgo/Dockerfile
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#1962 Use the new dnsperfgo client in dns load tests.
  clusterloader2/testing/load/configmap.yaml
  clusterloader2/testing/load/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#1970 Add CL2_CHECK_IF_PODS_ARE_UPDATED support to the huge-service config
  clusterloader2/testing/huge-service/modules/service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1973 Add support for integers in Exec measurement
  clusterloader2/pkg/measurement/common/exec.go
  clusterloader2/pkg/util/util.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#1974 Allow additional slow calls in huge-service test
  clusterloader2/testing/huge-service/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, kind/regression

#1972 Scrape cilium-operator Prometheus metrics
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorCiliumOperator.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/prometheus/scrape-cilium-operator.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved, ok-to-test

#1961 Added sample yamls for deploying dnsperfgo.
  dns/dnsperfgo/README.md
  dns/dnsperfgo/deployment.yaml
  dns/dnsperfgo/main.go
  dns/dnsperfgo/queries-cm.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/documentation, approved

#1977 Fix huge-service pod deletion
  clusterloader2/testing/huge-service/modules/service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#1976 Add WaitForFinishedJobs measurement
  clusterloader2/pkg/measurement/common/wait_for_jobs.go
  clusterloader2/pkg/measurement/util/informer/informer.go
  clusterloader2/testing/batch/config.yaml
  clusterloader2/testing/batch/job.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#1979 Extend P&F dashboard with additional metrics
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.dashboard.py
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test
