Repository kubernetes/perf-tests, pull requests merged in 2022-09, with the labels that each got.

#2138 Fall back to using ADC when setting up GCE PD CSI driver in CL2
  clusterloader2/run-e2e.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#2140 Add DNS lookup error percentage threshold instead of error count
  clusterloader2/pkg/measurement/common/generic_query_measurement.go
  clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#2139 Add dashboards for calls made from apiserver
  clusterloader2/pkg/prometheus/manifests/dashboards/master-comparison.json
  clusterloader2/pkg/prometheus/manifests/dashboards/master-dashboard.json
  clusterloader2/pkg/prometheus/manifests/dashboards/master_panels.py
Labels: lgtm, cncf-cla: yes, size/XL, kind/feature, approved, ok-to-test

#2064 Support custom azuredisk driver install url
  clusterloader2/run-e2e.sh
Labels: lgtm, cncf-cla: yes, size/XS, sig/windows, kind/feature, approved, ok-to-test

#2145 Add option to specify timeout for exec command
  clusterloader2/testing/load/config.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved
