Repository kubernetes/perf-tests, pull requests merged in 2022-07, with the labels that each got.

#2095 Implement profiling in clusterloader
  clusterloader2/cmd/clusterloader.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2094 Add GCP Compute API quotas usage measurement
  clusterloader2/go.mod
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/measurement/common/prometheus_measurement.go
  clusterloader2/pkg/measurement/util/prometheus.go
  clusterloader2/pkg/prometheus/clients/gcp_managed.go
  clusterloader2/pkg/prometheus/clients/in_cluster.go
  clusterloader2/pkg/prometheus/clients/interface.go
  clusterloader2/pkg/provider/aks.go
  clusterloader2/pkg/provider/autopilot.go
  clusterloader2/pkg/provider/aws.go
  clusterloader2/pkg/provider/eks.go
  clusterloader2/pkg/provider/gce.go
  clusterloader2/pkg/provider/gke.go
  clusterloader2/pkg/provider/gke_kubemark.go
  clusterloader2/pkg/provider/kcp.go
  clusterloader2/pkg/provider/kind.go
  clusterloader2/pkg/provider/kubemark.go
  clusterloader2/pkg/provider/local.go
  clusterloader2/pkg/provider/provider.go
  clusterloader2/pkg/provider/skeleton.go
  clusterloader2/pkg/provider/util.go
  clusterloader2/pkg/provider/vsphere.go
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, sig/scalability, size/L, approved

#2097 Add --dry-run flag
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/test/test.go
  verify/verify-flags/excluded-flags.txt
Labels: lgtm, cncf-cla: yes, size/M, approved

#2099 Enable violations for the advanced DNS test
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/XS, needs-ok-to-test, kind/feature, approved

#2100 Retry transient http2 errors
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/framework/client/objects_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2101 [Perfdash] Add support for ADC
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/gcs_metrics_bucket.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2102 Pass StepResult only as pointer as it contains lock which cannot be copied
  clusterloader2/pkg/test/interface.go
  clusterloader2/pkg/test/simple_reporter.go
  clusterloader2/pkg/test/step_summary.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2104 Cleanup of WaitForPods
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/measurement/common/network/network_performance_measurement.go
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
  clusterloader2/pkg/measurement/util/object_store.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
  clusterloader2/pkg/measurement/util/wait_for_pods.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#2106 Set backoff limit for load test job
  clusterloader2/testing/load/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2109 Fix perfdash for generic Prometheus measurements
  clusterloader2/pkg/measurement/common/generic_query_measurement.go
  clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/metrics-downloader.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2110 Change perfdash deployment's namespace
  perfdash/deployment.yaml
  perfdash/perfdash-service.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved
