Repository kubernetes/perf-tests, pull requests merged in 2022-06, with the labels that each got.

#2059 clusterloader2: Remove the file's dependency on gopath
  clusterloader2/pkg/config/template_functions.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2079 Make exec_deployment.yaml path configurable
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/measurement/common/api_availability_measurement.go
  clusterloader2/pkg/measurement/common/service_creation_latency.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#1854 Added developing measurement tutorial
  clusterloader2/docs/DEVELOPING_MEASUREMENT.md
Labels: lgtm, cncf-cla: yes, kind/documentation, size/XL, approved

#2084 Add custom nodeSelector for Prometheus
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2066 clusterloader2: Fix error of probes about metrics-server
  clusterloader2/pkg/measurement/common/probes/manifests/metricsServer/metrics-server-probe-rbac.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/metricsServer/metrics-server-prober-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/metricsServer/metrics-server-prober-rbac.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/metricsServer/metrics-server-prober-service.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/metricsServer/metrics-server-prober-serviceMonitor.yaml
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/serviceMonitor.yaml
  util-images/probes/Makefile
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/bug

#2080 Update CL2 APIResponsivenessPrometheus threasholds
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/slos/testdata/get_slo_failure.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/mutating_slo_failure.yaml
  clusterloader2/pkg/measurement/common/slos/testdata/namespace_list_slo_failure.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup, ok-to-test

#2085 Allow scaling Prometheus resource requests & limits
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2089 Clean up Prometheus-based measurements unit testing framework
  clusterloader2/pkg/measurement/common/cilium_endpoint_propagation_delay_test.go
  clusterloader2/pkg/measurement/common/container_restarts_test.go
  clusterloader2/pkg/measurement/common/executors/promql_executor.go
  clusterloader2/pkg/measurement/common/executors/utils.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/above_slow_count_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/below_slow_count_pass.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/cluster_list_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/get_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/mutating_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/namespace_list_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/rules.yml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/slo_pass.yaml
  clusterloader2/pkg/measurement/common/testdata/cilium_endpoint_propagation_delay/default_slo_fail.yaml
  clusterloader2/pkg/measurement/common/testdata/cilium_endpoint_propagation_delay/default_slo_pass.yaml
  clusterloader2/pkg/measurement/common/testdata/container_restarts/double_restart_of_apiserver.yaml
  clusterloader2/pkg/measurement/common/testdata/container_restarts/no_restarts.yaml
  clusterloader2/pkg/measurement/common/testdata/container_restarts/two_apiserver_replicas_restarts.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/cleanup

#2090 Add information about measurement unit testing to docs
  clusterloader2/docs/DEVELOPING_MEASUREMENT.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved

#2070 Fixed Docker build for networking performance issue: #2067
  network/benchmarks/netperf/Dockerfile
  network/benchmarks/netperf/Makefile
  network/benchmarks/netperf/go.mod
  network/benchmarks/netperf/go.sum
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, ok-to-test

#2088 Expose Windows metrics in perfdash
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2034 Add Windows measurements for soak tests
  clusterloader2/pkg/measurement/common/slos/windows_node_resource_usage.go
Labels: lgtm, cncf-cla: yes, sig/windows, size/L, kind/feature, approved, ok-to-test

#2091 Increase prometheus timeout
  clusterloader2/pkg/measurement/util/prometheus.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2074 Set CL2_API_AVAILABILITY_PERCENTAGE_THRESHOLD to 99.5 by default
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2087 fix issue-2081 delete namespace sometimes error
  clusterloader2/pkg/framework/framework.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, ok-to-test

#2072 Add measurement for dnsperfgo K8s hostnames test
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/dns/dns_performance-k8s-hostnames.go
  clusterloader2/pkg/measurement/common/dns/manifests/clusterrole.yaml
  clusterloader2/pkg/measurement/common/dns/manifests/clusterrolebinding.yaml
  clusterloader2/pkg/measurement/common/dns/manifests/dns-client.yaml
  clusterloader2/pkg/measurement/common/dns/manifests/serviceaccount.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test
