Repository kubernetes/perf-tests, pull requests merged in 2022-11, with the labels that each got.

#2173 Fix consecutive failed probes counting in API availability measurement
  clusterloader2/pkg/measurement/common/api_availability_metrics.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2180 bundle: Use apiServerMemoryProfile for memory profile
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2181 bundle: Add mutex profile for components other than etcd
  clusterloader2/pkg/measurement/common/bundle/test_metrics.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/cleanup

#2165 Improve error message on module parsing
  clusterloader2/pkg/test/modules.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2179 Disable resource usage measurement for Autopilot provider
  clusterloader2/pkg/measurement/common/resource_usage.go
  clusterloader2/pkg/provider/aks.go
  clusterloader2/pkg/provider/aws.go
  clusterloader2/pkg/provider/eks.go
  clusterloader2/pkg/provider/gce.go
  clusterloader2/pkg/provider/gke.go
  clusterloader2/pkg/provider/gke_kubemark.go
  clusterloader2/pkg/provider/kcp.go
  clusterloader2/pkg/provider/kind.go
  clusterloader2/pkg/provider/kubemark.go
  clusterloader2/pkg/provider/local.go
  clusterloader2/pkg/provider/provider.go
  clusterloader2/pkg/provider/skeleton.go
  clusterloader2/pkg/provider/vsphere.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2190 feat: allow overriding the storage class used for prometheus pvc
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2184 Job Startup Latency Measurement
  clusterloader2/pkg/measurement/common/job_lifecycle_latency.go
  clusterloader2/testing/batch/config.yaml
  clusterloader2/testing/batch/job.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#2193 Remove krzysied from OWNERS
  clusterloader2/OWNERS
  perfdash/OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2194 Add terminated watches metrics
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved, ok-to-test

#2189 fix: master kubelets service monitor in CL2
  clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2196 feat: allow overriding prometheus memory request
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2183 Turn storage scalability tests to green
  clusterloader2/testing/experimental/storage/pod-startup/config.yaml
Labels: lgtm, cncf-cla: yes, size/XS, sig/scalability, approved, kind/bug

#2198 [ClusterLoader2] Enable usage of public IPs for master scraping
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#2182 kube-proxy iptables partial restore failures
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#2200 CL2: Use embed FS instead of relying on $GOPATH.
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/test/simple_context.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#2201 Migrate prometheus manifests to embed FS
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/prometheus/manifests/grafana-dashboardDefinitions.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/cleanup

#2202 Migrate remaining manifests to embed
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/measurement/common/dns/dns_performance-k8s-hostnames.go
  clusterloader2/pkg/measurement/common/network/network_performance_measurement.go
  clusterloader2/pkg/measurement/common/probes/probes.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#2188 Add checking all IPs in Service reachibility verification
  clusterloader2/pkg/measurement/common/service_creation_latency.go
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#2209 Fix case when there are no replicas
  clusterloader2/pkg/test/simple_test_executor.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2210 Return summary with failed pods in WaitForControlledPodsRunning
  clusterloader2/go.mod
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/measurement/common/network/network_performance_measurement.go
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
  clusterloader2/pkg/measurement/util/pods.go
  clusterloader2/pkg/measurement/util/wait_for_pods.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test

#2206 Allow to optionally deploy kube-state-metrics scrapper on GKE clusters
  clusterloader2/pkg/provider/gke.go
Labels: lgtm, cncf-cla: yes, size/XS, needs-ok-to-test, approved

#2211 Remove unnecessary dependency on klog
  clusterloader2/go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, ok-to-test
