Repository kubernetes/perf-tests, pull requests merged in 2022-10, with the labels that each got.

#2146 Cleanup exact operation timeout experiment
  clusterloader2/pkg/measurement/common/wait_for_controlled_pods.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/cleanup

#2151 Add requireSamples field to GenericQueryMeasurement
  clusterloader2/examples/generic_query_example.yaml
  clusterloader2/pkg/measurement/common/generic_query_measurement.go
  clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#2152 Revert "Update profile.go"
  clusterloader2/pkg/measurement/common/profile.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2153 Change profile frequency to 5m
  clusterloader2/pkg/measurement/common/profile.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2154 Add more robust error handling for GMP-based Prometheus client
  clusterloader2/pkg/measurement/util/prometheus.go
  clusterloader2/pkg/prometheus/clients/gcp_managed.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2155 Add statefulset behind a headless service to huge-service test
  clusterloader2/testing/huge-service/config.yaml
  clusterloader2/testing/huge-service/modules/service.yaml
  clusterloader2/testing/huge-service/modules/statefulset.yaml
  clusterloader2/testing/huge-service/statefulset.yaml
  clusterloader2/testing/huge-service/statefulset_service.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2144 Add qperf support to netperf for network benchmarking
  network/benchmarks/netperf/Dockerfile
  network/benchmarks/netperf/launch.go
  network/benchmarks/netperf/nptest/nptest.go
  network/benchmarks/netperf/nptest/nptest_test.go
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#2160 Replace golint with revive
  .golangci.yml
  perfdash/parser.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#2161 Updated the go.mod with version 0.23.3
  clusterloader2/go.mod
  clusterloader2/go.sum
Labels: lgtm, cncf-cla: yes, size/XL, approved, ok-to-test

#2156 Add benchmark app
  util-images/request-benchmark/Dockerfile
  util-images/request-benchmark/Makefile
  util-images/request-benchmark/README.md
  util-images/request-benchmark/client.go
  util-images/request-benchmark/go.mod
  util-images/request-benchmark/go.sum
  util-images/request-benchmark/main.go
Labels: lgtm, cncf-cla: yes, size/XL, kind/feature, approved

#2162 Revert "Updated the go.mod with version 0.23.3"
  clusterloader2/go.mod
  clusterloader2/go.sum
Labels: lgtm, cncf-cla: yes, size/XL, approved

#2164 Add a health check to request benchmark
  util-images/request-benchmark/Makefile
  util-images/request-benchmark/main.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2163 Add request-benchmark CL2 scenario
  clusterloader2/testing/request-benchmark/cluster-role-binding.yaml
  clusterloader2/testing/request-benchmark/cluster-role.yaml
  clusterloader2/testing/request-benchmark/config.yaml
  clusterloader2/testing/request-benchmark/configmap.yaml
  clusterloader2/testing/request-benchmark/deployment.yaml
  clusterloader2/testing/request-benchmark/modules/benchmark-deployment.yaml
  clusterloader2/testing/request-benchmark/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#2167 Updated go.mod with version 0.22.15
  clusterloader2/go.mod
  clusterloader2/go.sum
Labels: lgtm, cncf-cla: yes, size/L, approved, ok-to-test

#2159 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#2168 Extend benchmark duration
  clusterloader2/testing/request-benchmark/config.yaml
  clusterloader2/testing/request-benchmark/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug

#2169 Bump benchmark requests
  clusterloader2/testing/request-benchmark/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2171 Reduce benchmark requests
  clusterloader2/testing/request-benchmark/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup
