Repository kubernetes/perf-tests, pull requests merged in 2022-02, with the labels that each got.

#1978 Add multiple queries and checks to generic query measurement
  clusterloader2/examples/generic_query_example.yaml
  clusterloader2/pkg/measurement/common/generic_query_measurement.go
  clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
  clusterloader2/pkg/util/util.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#1984 Add image for sleep command
  util-images/sleep/Dockerfile
  util-images/sleep/Makefile
  util-images/sleep/README.md
  util-images/sleep/main.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#1986 update sleep image to optionally handle SIGTERM
  util-images/sleep/main.go
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#1987 Update sleep image to 0.0.2
  util-images/sleep/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1989 Add a CL2 parameter for modifying the Prometheus memory limit
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, needs-ok-to-test, kind/feature, approved

#1993 Use community-owned GCS bucket for Golang scripts
  golang/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1995 Add PROMETHEUS_SCRAPE_MASTER_KUBELETS
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/master-ip/master-serviceMonitor.yaml
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/XS, approved

#1994 Add sleep bin to PATH
  util-images/sleep/Dockerfile
  util-images/sleep/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved
