Repository kubernetes/perf-tests, pull requests merged in 2023-12, with the labels that each got.

#2453 Update k8s.io/kubernetes to fix CVE
  slo-monitor/go.mod
  slo-monitor/go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2421 Migrate to github.com/google/safetext/yamltemplate
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/config/template_functions.go
  clusterloader2/pkg/config/template_provider.go
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/default/kube-proxy-service.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#2462 Bump up slo-monitor to 0.15.6
  slo-monitor/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#2486 Update x/crypto to v0.17.0
  clusterloader2/go.mod
  clusterloader2/go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug

#2482 [CL2] Follow up to safetext migration
  clusterloader2/pkg/prometheus/manifests/0prometheus-operator-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug
