Repository kubernetes/perf-tests, pull requests merged in 2023-05, with the labels that each got.

#2205 clusterloader2: use new apiserver latency SLI
  clusterloader2/examples/generic_query_example.yaml
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/measurement/common/metrics_server_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/above_slow_count_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/below_slow_count_pass.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/cluster_list_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/get_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/mutating_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/namespace_list_slo_failure.yaml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/rules.yml
  clusterloader2/pkg/measurement/common/testdata/api_responsiveness_prometheus/slo_pass.yaml
  clusterloader2/pkg/measurement/interface.go
  clusterloader2/pkg/measurement/manager.go
  clusterloader2/pkg/measurement/util/metrics.go
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved, kind/cleanup

#2259 Update to go 1.20
  slo-monitor/Makefile
  slo-monitor/go.mod
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, ok-to-test

#2261 watch-list: define resources request and limit (mem, cpu) for the test pod
  clusterloader2/testing/watch-list/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2260 API Streaming test: allow for overwrite enableWatchListFeature flag
  clusterloader2/testing/watch-list/config.yaml
  clusterloader2/testing/watch-list/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2258 Don't use default kubeconfig for clusterloader
  clusterloader2/run-e2e.sh
Labels: lgtm, cncf-cla: yes, size/M, approved

#2264 Add option to disable pvc for prometheus
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2265 Scrape k8s apiserver only for aws provider
  clusterloader2/pkg/provider/aws.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug

#2266 perf-dash: add "benchmark" as name also for BenchmarkPerfScheduling
  perfdash/config.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/failing-test, approved, kind/bug

#2267 Fix BenchmarkPerfResults name. Release perfdash 2.46
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2243 Fix CEP propagation delay measurement
  clusterloader2/pkg/measurement/common/cilium_endpoint_propagation_delay.go
Labels: lgtm, cncf-cla: yes, size/S, needs-ok-to-test, approved, kind/bug

#2268 watch-list: allow for specifying custom api latency thresholds
  clusterloader2/testing/overrides/watch_list_off.yaml
  clusterloader2/testing/watch-list/config.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#2276 watch-list: define a job type for the perf-dashboard
  perfdash/config.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2277 Release perfdash 2.47
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup
