Repository kubernetes/perf-tests, pull requests merged in 2023-06, with the labels that each got.

#2281 watch-list/job: run two replicas per namespace
  clusterloader2/testing/watch-list/config.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#2285 Bump dnsperfgo to 1.4.0
  dns/dnsperfgo/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2286 CL2 load test bump dnsperfgo image to 1.4.0
  clusterloader2/testing/load/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2234 Add network policy enforcement latency measurement
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/measurement/common/network-policy/manifests/clusterrole.yaml
  clusterloader2/pkg/measurement/common/network-policy/manifests/clusterrolebinding.yaml
  clusterloader2/pkg/measurement/common/network-policy/manifests/dep-test-client-pod-creation.yaml
  clusterloader2/pkg/measurement/common/network-policy/manifests/dep-test-client-policy-creation.yaml
  clusterloader2/pkg/measurement/common/network-policy/manifests/policy-egress-allow-apiserver.yaml
  clusterloader2/pkg/measurement/common/network-policy/manifests/policy-egress-allow-target-pods.yaml
  clusterloader2/pkg/measurement/common/network-policy/manifests/policy-load.yaml
  clusterloader2/pkg/measurement/common/network-policy/manifests/serviceaccount.yaml
  clusterloader2/pkg/measurement/common/network-policy/network-policy-enforcement-latency.go
Labels: lgtm, cncf-cla: yes, size/XL, kind/feature, approved

#2283 Allow configuration of interval time between pings for InClusterNetworkLatency probe.
  clusterloader2/pkg/measurement/common/probes/manifests/ping-client-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/testing/huge-service/modules/measurements.yaml
  clusterloader2/testing/load/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved, ok-to-test

#2251 Add network policy enforcement latency measurement to load test
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorNetPolicyClient.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/daemonset.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/modules/measurements.yaml
  clusterloader2/testing/load/modules/network-policy/net-policy-enforcement-latency.yaml
  clusterloader2/testing/load/modules/network-policy/net-policy-metrics.yaml
  clusterloader2/testing/load/modules/reconcile-objects.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#2289 chore: remove refs to deprecated io/ioutil
  dns/dnsperfgo/main.go
Labels: lgtm, cncf-cla: yes, size/XS, needs-ok-to-test, approved, kind/cleanup

#2291 Compute gocmp.Diff lazily in ClusterLoader2
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
Labels: lgtm, cncf-cla: yes, size/S, approved

#2293 Include control plane node role when checking for control plane node
  clusterloader2/pkg/measurement/common/scheduler_latency.go
  clusterloader2/pkg/measurement/util/gatherers/container_resource_gatherer.go
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/provider/gce.go
  clusterloader2/pkg/util/cluster.go
  clusterloader2/pkg/util/cluster_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, ok-to-test
