Repository kubernetes/perf-tests, pull requests merged in 2023-07, with the labels that each got.

#2295 Take full duration into account in Prometheus-based measurements
  clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
  clusterloader2/pkg/measurement/util/prometheus.go
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug

#2298 Enable treating threshold as a lower bound in generic measurement
  clusterloader2/pkg/measurement/common/generic_query_measurement.go
  clusterloader2/pkg/measurement/common/generic_query_measurement_test.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2299 Improve request benchmark test
  clusterloader2/testing/request-benchmark/config.yaml
  clusterloader2/testing/request-benchmark/configmap.yaml
  clusterloader2/testing/request-benchmark/deployment.yaml
  clusterloader2/testing/request-benchmark/modules/benchmark-deployment.yaml
  clusterloader2/testing/request-benchmark/modules/measurements.yaml
  util-images/request-benchmark/Makefile
  util-images/request-benchmark/client.go
  util-images/request-benchmark/main.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2303 issue:2287: decrease the number of informers to see impact on latency
  clusterloader2/testing/watch-list/config.yaml
  clusterloader2/testing/watch-list/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2304 Update golang compiler for golang tip job
  golang/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2305 issue:2287: slightly increase the number of informers to see impact on latency
  clusterloader2/testing/watch-list/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2306 issue:2287: find maximum number of informers that doesn't impact latency.
  clusterloader2/testing/watch-list/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved
