Repository kubernetes/perf-tests, pull requests merged in 2023-02, with the labels that each got.

#2226 Network policy latency test clients v.0.0.1
  network/tools/network-policy-enforcement-latency/Makefile
  network/tools/network-policy-enforcement-latency/README.md
  network/tools/network-policy-enforcement-latency/go.mod
  network/tools/network-policy-enforcement-latency/go.sum
  network/tools/network-policy-enforcement-latency/pkg/metrics/metrics.go
  network/tools/network-policy-enforcement-latency/pkg/utils/utils.go
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/Dockerfile
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/example-manifests/permissions.yaml
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/example-manifests/policy-allow-egress-to-target-pods.yaml
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/example-manifests/target-deployment.yaml
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/example-manifests/test-client-deployment.yaml
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/main.go
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/test-client/client.go
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/Dockerfile
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/example-manifests/permissions.yaml
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/example-manifests/policy-allow-egress-to-target-pods.yaml
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/example-manifests/policy-deny-egress-to-target-pods.yaml
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/example-manifests/target-deployment.yaml
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/example-manifests/test-client-deployment.yaml
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/main.go
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/test-client/client.go
Labels: lgtm, cncf-cla: yes, size/XXL, kind/feature, approved

#2233 Fix metrics server to run until the app is shut down and register multiple metrics correctly
  network/tools/network-policy-enforcement-latency/pkg/metrics/metrics.go
  network/tools/network-policy-enforcement-latency/pkg/utils/utils.go
  network/tools/network-policy-enforcement-latency/pod-creation-reachability-latency/test-client/client.go
  network/tools/network-policy-enforcement-latency/policy-creation-enforcement-latency/test-client/client.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug

#2232 Switch to registry.k8s.io
  clusterloader2/docs/GETTING_STARTED.md
  clusterloader2/drivers/gcp-csi-driver-stable.yaml
  clusterloader2/pkg/execservice/manifest/exec_deployment.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/deployment.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/metrics-server/resourceConsumer.yaml
  clusterloader2/testing/density/deployment.yaml
  clusterloader2/testing/density/scheduler/custom-scheduler-metrics/deployment-custom-schd-sample.yaml
  clusterloader2/testing/density/scheduler/pod-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-anti-affinity/deployment.yaml
  clusterloader2/testing/density/scheduler/pod-topology-spread/deployment.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/configmap/deployment_with_configmap.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/downwardapi/deployment_with_downwardapi.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/emptydir/deployment_with_emptydir.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/genericephemeralinline/deployment_with_inline.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/persistentvolume/deployment_with_pvc.yaml
  clusterloader2/testing/experimental/storage/pod-startup/volume-types/secret/deployment_with_secret.yaml
  clusterloader2/testing/load/config.yaml
  clusterloader2/testing/load/daemonset.yaml
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/job.yaml
  clusterloader2/testing/load/modules/reconcile-objects.yaml
  clusterloader2/testing/load/simple-deployment.yaml
  clusterloader2/testing/load/statefulset.yaml
  clusterloader2/testing/node-throughput/config.yaml
  clusterloader2/testing/windows-tests/config.yaml
  dns/README.md
  dns/cluster/dnsperf-deploy.yaml
  dns/cluster/dnsperf.yaml
  dns/cluster/kube-dns-deployment.yaml
  slo-monitor/slo-monitor-deployment.yaml
  slo-monitor/slo-monitor-pod.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#2235 Added parsing of huge-service messurements to pref dash
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2238 Allow specifying verb in request-benchmark
  util-images/request-benchmark/main.go
Labels: lgtm, cncf-cla: yes, size/XS, approved
