Repository kubernetes/perf-tests, pull requests merged in 2023-03, with the labels that each got.

#2239 Update to go 1.19
  slo-monitor/Makefile
  slo-monitor/go.mod
  slo-monitor/go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#2240 Add a way to customize namespace deletion timeout
  clusterloader2/api/default.go
  clusterloader2/api/types.go
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/framework/framework.go
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/measurement/common/network/network_performance_measurement.go
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/pkg/test/simple_test_executor.go
  clusterloader2/testing/huge-service/config.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2242 fix(clusterloader2): fix daemonset node counter
  clusterloader2/pkg/measurement/util/runtimeobjects/replicaswatcher.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects.go
  clusterloader2/pkg/measurement/util/runtimeobjects/runtimeobjects_test.go
Labels: lgtm, cncf-cla: yes, needs-ok-to-test, size/L, approved, kind/bug
