Repository kubernetes/perf-tests, pull requests merged in 2024-10, with the labels that each got.

#2919 Update kube-state-metrics manifests to the latest release
  clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/clusterRole.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/clusterRoleBinding.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/deployment.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/service.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/serviceAccount.yaml
  clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/serviceMonitor.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#2794 CL2: Add isFatal param to WaitForPods and enable failing measurements
  clusterloader2/pkg/errors/error_list.go
  clusterloader2/pkg/errors/fatal_error.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
  clusterloader2/pkg/measurement/measurement_executor.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved, ok-to-test

#2808 Add option to load perf dash metrics from local artifacts directory
  .gitignore
  perfdash/.gitignore
  perfdash/Makefile
  perfdash/local_metrics_dir.go
  perfdash/metrics-downloader.go
  perfdash/perfdash.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#2706 allows for the exec_service pod image to be pulled from a custom repo
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/execservice/exec_service.go
  clusterloader2/pkg/execservice/manifest/exec_deployment.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved, lifecycle/rotten, ok-to-test

#2943 watchlist: bring the initial informers count back
  clusterloader2/testing/watch-list/config.yaml
  clusterloader2/testing/watch-list/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2968 Add flags for resources of DNS propagation prober
  clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/propagation_metric.go
Labels: lgtm, cncf-cla: yes, size/S, needs-ok-to-test, kind/feature, approved, kind/api-change

#2944 Change perf-dash logs bucket to kubernetes-ci-logs
  perfdash/config.go
  perfdash/perfdash.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug

#2972 Release new version of perfdash
  perfdash/Makefile
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved
