Repository kubernetes/perf-tests, pull requests merged in 2024-05, with the labels that each got.

#2632 New Provider: Adding a KubeStellar provider
  clusterloader2/cmd/clusterloader.go
  clusterloader2/pkg/provider/constants.go
  clusterloader2/pkg/provider/ks.go
  clusterloader2/pkg/provider/provider.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved, ok-to-test

#2667 scrape network policies
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorKubeNetworkPolicies.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/prometheus/scrape-kube-network-policies.yaml
Labels: lgtm, cncf-cla: yes, size/M, approved

#2633 New Tuning Set: Adding a Poisson tuning set
  clusterloader2/api/types.go
  clusterloader2/api/validation.go
  clusterloader2/api/validation_test.go
  clusterloader2/pkg/tuningset/poisson_load.go
  clusterloader2/pkg/tuningset/simple_tuning_set_factory.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test

#2682 Add direct scheduler throughput test suite
  clusterloader2/testing/scheduler-throughput/config.yaml
  clusterloader2/testing/scheduler-throughput/pod-default.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved
