Repository kubernetes/perf-tests, pull requests merged in 2024-09, with the labels that each got.

#2765 Enable DNS propagation measurement for huge-service test
  clusterloader2/testing/huge-service/config.yaml
  clusterloader2/testing/huge-service/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved, ok-to-test

#2861 Fix image parametrization in load config
  clusterloader2/testing/load/deployment.yaml
  clusterloader2/testing/load/job.yaml
  clusterloader2/testing/load/statefulset.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, ok-to-test

#2877 Bump version of go compiler that bootstraps golang tip test to 1.23.0
  golang/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, ok-to-test

#2898 CL2: Add refreshInterval param to WaitForNodes and WaitForRunningPods measurements
  clusterloader2/pkg/measurement/common/wait_for_nodes.go
  clusterloader2/pkg/measurement/common/wait_for_pods.go
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved, ok-to-test

#2862 Label dependabot PRs as ok-to-test by default
  .github/dependabot.yml
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#2914 Add option to tune sync interval
  perfdash/Dockerfile
  perfdash/Makefile
  perfdash/deployment.yaml
  perfdash/perfdash.go
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved, kind/bug
