Repository kubernetes/perf-tests, pull requests merged in 2024-04, with the labels that each got.

#2634 Add aojea to network folder
  network/OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2642 Add retry to exec measurement
  clusterloader2/pkg/measurement/common/exec.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2620 increase the duration to 15m
  clusterloader2/testing/list/config.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#2648 Bump golang version in perfdash and add network performance dashboard
  perfdash/Dockerfile
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
  perfdash/go.mod
  perfdash/go.sum
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#2649 DNS propagation measurement in CL2
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-deployment.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-rbac.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-service.yaml
  clusterloader2/pkg/measurement/common/probes/manifests/dnsPropagation/dns-propagation-prober-serviceMonitor.yaml
  clusterloader2/pkg/measurement/common/probes/probes.go
  clusterloader2/pkg/measurement/common/probes/propagation_metric.go
  clusterloader2/pkg/prometheus/manifests/prometheus-rules.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test

#2651 Add pod monitor for cilium agent and operator
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorCiliumAgent.yaml
  clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorCiliumOperator.yaml
  clusterloader2/pkg/prometheus/prometheus.go
  clusterloader2/testing/prometheus/scrape-cilium-operator.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2666 Update x/crypto to v0.17.0
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/measurement/common/executors/utils.go
  clusterloader2/pkg/test/modules.go
  perfdash/metrics-downloader.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug

#2665 Update x/crypto to v0.17.0
  clusterloader2/go.mod
  clusterloader2/go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug

#2664 Update x/crypto to v0.17.0
  clusterloader2/go.mod
  clusterloader2/go.sum
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug
