Repository kubernetes/perf-tests, pull requests merged in 2024-07, with the labels that each got.

#2757 prometheus: add optional path with additional manifests
  clusterloader2/pkg/config/cluster.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved

#2767 upgrade go version and bump tag for slo-monitor
  slo-monitor/Makefile
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup, tide/merge-method-squash, ok-to-test

#2773 Fix Kind pluralization.
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/framework/client/objects.go
  clusterloader2/pkg/framework/client/objects_test.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, ok-to-test

#2772 Grammar fixes for the CL2 README.md
  clusterloader2/README.md
Labels: lgtm, cncf-cla: yes, kind/documentation, size/L, approved

#2764 adds WatchList Latency to APIResponsivenessPrometheus
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus.go
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#2799 Bump priorityclass of prometheus
  clusterloader2/pkg/prometheus/manifests/0prometheus-priorityclass.yaml
  clusterloader2/pkg/prometheus/manifests/grafana-deployment.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-prometheus.yaml
  clusterloader2/pkg/prometheus/manifests/prometheus-resourceQuota.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, ok-to-test
