Repository kubernetes/perf-tests, pull requests merged in 2024-11, with the labels that each got.

#2971 Add support for Azure Managed Prometheus in Clusterloader2
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/prometheus/clients/aks_managed.go
  clusterloader2/pkg/provider/aks.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved, ok-to-test

#2979 Bump kubernetes dependency in jsonify
  dns/jsonify/go.mod
  dns/jsonify/go.sum
Labels: lgtm, cncf-cla: yes, size/XS, approved

#3031 watchlist: decrease the number of informers to 6 to confirm no impact on latency
  clusterloader2/testing/watch-list/config.yaml
  clusterloader2/testing/watch-list/job.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved

#3032 Add request count to watchlist tests
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved
