Repository kubernetes/perf-tests, pull requests merged in 2025-01, with the labels that each got.

#3078 clusterloader2: Avoid logging and awaiting waitgroup when chaosmonkey is disabled
  clusterloader2/pkg/chaos/monkey.go
  clusterloader2/pkg/measurement/common/chaos_monkey_measurement.go
  clusterloader2/pkg/test/simple_test_executor.go
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/bug, ok-to-test

#3086 Cleanup klog in clusterloader
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/measurement/common/slos/api_responsiveness_prometheus_test.go
  clusterloader2/pkg/measurement/util/informer/informer.go
  clusterloader2/pkg/prometheus/clients/aks_managed.go
Labels: lgtm, cncf-cla: yes, size/M, approved

#3088 Bump clusterloader deps
  clusterloader2/cmd/clusterloader.go
  clusterloader2/go.mod
  clusterloader2/go.sum
  clusterloader2/pkg/flags/flags.go
  clusterloader2/pkg/imagepreload/imagepreload.go
  clusterloader2/pkg/prometheus/experimental.go
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/L, approved

#3099 Remove test exclusions
  verify/test.sh
Labels: lgtm, cncf-cla: yes, size/S, approved

#3100 Bump clusterloader deps to 1.31
  clusterloader2/go.mod
  clusterloader2/go.sum
Labels: lgtm, cncf-cla: yes, size/XXL, approved

#3098 Update ClusterLoader2's temp KubeConfig PKI for ServiceAccount
  clusterloader2/run-e2e.sh
Labels: lgtm, cncf-cla: yes, size/S, approved, kind/bug, kind/deprecation

#3141 Rewrite list benchmark to validate large list
  clusterloader2/testing/list/README.md
  clusterloader2/testing/list/config.yaml
  clusterloader2/testing/list/modules/list-benchmark.yaml
  clusterloader2/testing/list/modules/measurements.yaml
  clusterloader2/testing/list/secret.yaml
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#3144 Fix go version and deployment.yaml
  perfdash/Dockerfile
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug
