Repository kubernetes/perf-tests, pull requests merged in 2025-02, with the labels that each got.

#3143 Rewrite request-benchmark to not load responses in memory
  util-images/request-benchmark/Makefile
  util-images/request-benchmark/client.go
  util-images/request-benchmark/main.go
Labels: lgtm, cncf-cla: yes, size/L, kind/feature, approved

#3160 Add support for DNSPropagation measurement to perfdash
  perfdash/config.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#3162 Use constant resources for list benchmark deployment
  clusterloader2/testing/list/config.yaml
  clusterloader2/testing/list/deployment.yaml
  clusterloader2/testing/list/modules/list-benchmark.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/feature, approved

#3163 Add instructions to run list benchmark locally
  clusterloader2/testing/list/README.md
Labels: lgtm, cncf-cla: yes, size/M, kind/documentation, approved

#3200 Add missing kind file with configuration to run tests locally
  clusterloader2/testing/list/kind.yaml
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved
