Repository kubernetes/perf-tests, pull requests merged in 2025-06, with the labels that each got.

#3375 Clusterloader2 docs update
  clusterloader2/docs/GETTING_STARTED.md
Labels: lgtm, cncf-cla: yes, size/S, kind/documentation, approved, ok-to-test

#3387 Avoid building kube-cross (inject `.go-version` instead)
  golang/build-kubernetes.sh
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#3388 Create a temp commit for the .go-version edit
  golang/build-kubernetes.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/cleanup

#3395 add mengqiy to OWNERS
  OWNERS_ALIASES
Labels: lgtm, cncf-cla: yes, size/XS, approved

#3397 update thresholds for dra test Churn phase
  clusterloader2/testing/dra/config.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved

#3399 implement a PrometheusSchedulingMetrics Measurement and Gatherer
  clusterloader2/pkg/measurement/common/prometheus_scheduler_latency.go
  clusterloader2/testing/dra/README.md
  clusterloader2/testing/dra/config.yaml
Labels: lgtm, cncf-cla: yes, size/L, approved

#3428 tuningSet: fix TimeLimitedLoad for zero actions
  clusterloader2/pkg/tuningset/time_limited.go
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug
