Repository kubernetes/perf-tests, pull requests merged in 2025-09, with the labels that each got.

#3477 Make image preload timeout configurable
  clusterloader2/pkg/imagepreload/imagepreload.go
Labels: lgtm, cncf-cla: yes, size/XS, kind/feature, approved

#3386 Add cloud build
  util-images/Makefile
  util-images/access-tokens/Makefile
  util-images/cloudbuild.yaml
  util-images/containerd/Makefile
  util-images/probes/Makefile
  util-images/request-benchmark/Makefile
  util-images/scratch/Makefile
  util-images/sleep/Makefile
  util-images/watch-list/Makefile
Labels: lgtm, cncf-cla: yes, size/M, approved, kind/cleanup

#3623 Add serathius to owners of list benchmark
  clusterloader2/testing/list/OWNERS
Labels: lgtm, cncf-cla: yes, size/XS, approved

#3574 Add measurement to check memory usage in benchmark list job
  clusterloader2/testing/list/modules/measurements.yaml
Labels: lgtm, cncf-cla: yes, size/S, approved, ok-to-test

#3592 Add parser for etcd API benchmarks
  perfdash/Makefile
  perfdash/config.go
  perfdash/deployment.yaml
Labels: lgtm, cncf-cla: yes, size/M, kind/feature, approved
