Repository kubernetes/perf-tests, pull requests merged in 2025-04, with the labels that each got.

#3302 Make Prometheus secret creation idempotent
  clusterloader2/pkg/prometheus/prometheus.go
Labels: lgtm, cncf-cla: yes, size/M, approved, ok-to-test

#3137 fix: neg-latency quotes typo on waitAfterDelete
  clusterloader2/testing/neg/config.yaml
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug, lifecycle/stale

#3304 Remove previous go instalation in build-go.sh, bump go compiler to 1.24.2
  golang/Makefile
  golang/build-go.sh
Labels: lgtm, cncf-cla: yes, size/XS, approved, kind/bug
